import './competition.css'
import { useEffect, useRef, useState } from 'react'
import { ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronRight, Clock3, Flag, ListOrdered, Share2, Sparkles, TrendingUp, Users } from 'lucide-react'
import { Avatar, DemoLabel, Empty, Modal, Tag } from '../../components/ui'
import { nextClassGap } from './logic'
import { DEMO_STUDENT_ID } from './useCompetition'
import type { CompetitionController } from './useCompetition'
import type { CompetitionPhase, CompetitionView } from './types'

export function CompetitionCard({ controller: c, onOpen, onRanking }: { controller: CompetitionController; onOpen: () => void; onRanking: () => void }) {
  const closed = c.attempt.phase === 'finished'
  const days = Math.ceil((Date.parse(c.event.endsAt) - Date.parse(c.event.referenceTime)) / 86_400_000)
  const gap = nextClassGap(c.rankings, c.classId)
  return <section className={`competition-entry ${closed ? 'finished' : ''}`} aria-label="Еженедельный квиз">
    <div className="competition-entry-top"><span><Sparkles size={15} />ЕЖЕНЕДЕЛЬНЫЙ КВИЗ</span><Tag>{closed ? 'Итоги недели' : c.attempt.phase === 'last-day' ? '24 часа' : `${days} дня`}</Tag></div>
    <div className="competition-entry-heading"><div><h2>Битва классов</h2><p>{c.quiz.topic}</p></div><span className="competition-rank-mark">{c.mine.position}<ArrowUpRight size={22} /></span></div>
    {closed ? <><div className="competition-winners">{c.rankings.slice(0, 3).map((team, i) => <span key={team.classId}><small>{['🥇', '🥈', '🥉'][i]}</small>{team.name}</span>)}</div><p className="competition-finished-copy"><strong>{c.mine.name} занял {c.mine.position} место</strong>{c.result && <span>Твой результат: {c.result.correct} / {c.result.total}</span>}</p></> : <><div className="competition-entry-stats"><span>Твой класс<strong>{c.mine.name}</strong></span><span>Сейчас<strong>{c.mine.position} место</strong></span><span>Очки класса<strong>{c.mine.points}</strong></span></div><div className="competition-entry-gap"><TrendingUp size={15} /><span>{gap ? `До ${gap.position} места — ${gap.points} очков` : 'Ты в команде лидеров. Держим волну!'}</span><small>До конца: {c.attempt.phase === 'last-day' ? '24 часа' : `${days} дня`}</small></div></>}
    <div className="competition-entry-actions">{closed ? <><button className="button competition-closed" disabled><Flag size={17} />Квиз завершён</button><button className="competition-secondary" onClick={onRanking}>Итоги<ArrowRight size={16} /></button></> : <><button className="button competition-primary" onClick={onOpen}>{c.result ? 'Посмотреть результаты' : c.attempt.answers.length ? 'Продолжить квиз' : 'Пройти квиз'}<ArrowRight size={17} /></button><button className="competition-secondary" onClick={onRanking} aria-label="Открыть рейтинг"><ListOrdered size={21} /></button></>}</div>
  </section>
}

export function CompetitionScreen({ controller: c, view, onView, onBack, onAnswer, onPhase }: { controller: CompetitionController; view: Exclude<CompetitionView, null>; onView: (view: Exclude<CompetitionView, null>) => void; onBack: () => void; onAnswer: (questionId: string, optionId: string) => void; onPhase: (phase: CompetitionPhase) => void }) {
  const [sharing, setSharing] = useState<'result' | 'invite' | null>(null)
  const [demoControls, setDemoControls] = useState(false)
  const gap = nextClassGap(c.rankings, c.classId)
  const result = c.result
  const resultClass = c.rankings.find(team => team.classId === result?.classId) ?? c.mine
  return <div className="competition-page">
    <div className="competition-page-nav"><button className="back-link" onClick={onBack}><ArrowLeft size={17} />К ленте</button><button className="competition-demo-control" onClick={() => setDemoControls(true)}><DemoLabel>Демо события</DemoLabel></button></div>
    {view === 'quiz' && !result && c.attempt.phase !== 'finished' && <QuizScreen controller={c} onAnswer={onAnswer} />}
    {view === 'result' && result && <>
      <span className="eyebrow">ТВОЙ ВКЛАД В ОБЩУЮ ВОЛНУ</span>
      <div className="quiz-result-hero"><span className="result-kicker"><Check size={15} />КВИЗ ПРОЙДЕН</span><div className="quiz-result-score"><strong>{result.correct}</strong><span>из {result.total}</span></div><h1>{result.correct >= 7 ? 'Отличный результат!' : result.correct >= 4 ? 'Хорошее начало!' : 'Каждая попытка — опыт.'}</h1><p>{result.correct >= 7 ? 'И личная победа, и помощь своим.' : 'Ты дошёл до финиша. Новая неделя — новая возможность.'}</p><span className="result-abstract-star">✳</span></div>
      <div className="quiz-score-cards"><div><span>Ты получил</span><strong>{result.personalPoints}<small>очков</small></strong><p>За правильные ответы</p></div><div><span>Вклад в рейтинг {resultClass.name}</span><strong>+{result.classPoints}<small>очков</small></strong><p>К командному результату</p></div></div>
      <div className="class-movement-card"><div className="class-avatar">{resultClass.name}</div><div><strong>{result.positionAfter < result.positionBefore ? `${resultClass.name} поднялся с ${result.positionBefore}-го на ${result.positionAfter}-е место` : `${resultClass.name} сейчас на ${result.positionAfter} месте`}</strong><p>{gap ? `До ${gap.className} — ${gap.points} очков. Вместе ближе.` : 'Твой класс на первом месте. Хорошая команда!'}</p></div><span>{result.positionBefore}<ArrowRight size={15} />{result.positionAfter}</span></div>
      <button className="button primary full competition-main-action" onClick={() => onView('ranking')}>Посмотреть рейтинг<ArrowRight size={18} /></button><button className="button secondary full" onClick={() => setSharing('result')}><Share2 size={17} />Поделиться результатом</button>
      <div className="result-next-week"><Clock3 size={18} /><div><strong>На следующей неделе — новая битва</strong><p>А пока можно позвать одноклассников: каждый ответ помогает.</p></div></div>
    </>}
    {view === 'ranking' && <Ranking controller={c} onInvite={() => setSharing('invite')} onResults={() => onView(result ? 'result' : 'quiz')} />}
    {(view === 'result' && !result || view === 'quiz' && c.attempt.phase === 'finished') && <><Empty title="Эта битва уже завершилась">Посмотри, как выступил твой класс.</Empty><button className="button primary full" onClick={() => onView('ranking')}>Посмотреть рейтинг<ArrowRight size={17} /></button></>}
    {sharing && <Modal title={sharing === 'result' ? 'Твой результат — на одной волне' : 'Позови своих'} onClose={() => setSharing(null)}>
      <div className="competition-share-card"><span className="eyebrow">МАЯК · БИТВА КЛАССОВ</span><h3>{sharing === 'result' ? `${result?.correct} / ${result?.total}` : `Вместе за ${c.mine.name}`}</h3><p>{sharing === 'result' ? `${result?.personalPoints} личных очков · +${result?.classPoints} классу` : gap ? `До ${gap.className} — всего ${gap.points} очков` : 'Каждый правильный ответ помогает команде'}</p><span>{c.quiz.topic}<span>✦</span></span></div>
      <label className="field-label" htmlFor="competition-share-text">Текст для своих</label><textarea id="competition-share-text" className="input share-text" readOnly value={sharing === 'result' ? `Я прошёл квиз «${c.quiz.title}»: ${result?.correct} из ${result?.total}! Принёс ${result?.classPoints} очков классу ${resultClass.name}. Присоединяйся к битве классов в Маяке 💜` : `Ребят, поможем ${c.mine.name} подняться выше! В Маяке идёт квиз «${c.quiz.title}»: ${c.quiz.questions.length} вопросов, каждый верный ответ приносит очко классу. Кто с нами?`} /><p className="competition-share-note">Демо-карточка для обмена. Системная отправка пока не подключена.</p><button className="button primary full" onClick={() => setSharing(null)}>Готово<Check size={17} /></button>
    </Modal>}
    {demoControls && <Modal title="Проверить состояния события" onClose={() => setDemoControls(false)}><p className="modal-description">Можно посмотреть последний день и итоги, сохранив свою попытку и результат.</p><div className="competition-phase-options">{([{ id: 'active', title: 'Идёт квиз', description: 'До конца 2 дня' }, { id: 'last-day', title: 'Последние сутки', description: '24 часа и напоминание в школьной ленте' }, { id: 'finished', title: 'Квиз завершён', description: 'Итоги: 10А, 9Б, 8Б' }] as const).map(phase => <button key={phase.id} aria-pressed={c.attempt.phase === phase.id} onClick={() => { onPhase(phase.id); setDemoControls(false); if (phase.id === 'finished') onView('ranking') }}><span><strong>{phase.title}</strong><small>{phase.description}</small></span>{c.attempt.phase === phase.id ? <Check size={18} /> : <ChevronRight size={18} />}</button>)}</div><p className="competition-share-note">Это переключение демо-данных, без настоящего таймера и push-уведомлений.</p></Modal>}
  </div>
}

function QuizScreen({ controller: c, onAnswer }: { controller: CompetitionController; onAnswer: (questionId: string, optionId: string) => void }) {
  const index = c.attempt.answers.length
  const question = c.quiz.questions[index]
  const heading = useRef<HTMLHeadingElement>(null)
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const [transitioning, setTransitioning] = useState(false)
  useEffect(() => { heading.current?.focus({ preventScroll: true }) }, [question?.id])
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current) }, [])
  if (!question) return null
  return <div className="quiz-play"><div className="quiz-progress-heading"><span>{c.quiz.topic}</span><strong>{index + 1} / {c.quiz.questions.length}</strong></div><div className="quiz-progress-bar" role="progressbar" aria-label="Прогресс квиза" aria-valuemin={1} aria-valuemax={c.quiz.questions.length} aria-valuenow={index + 1}><span style={{ width: `${(index + 1) / c.quiz.questions.length * 100}%` }} /></div><div className="quiz-question-card" key={question.id}><span className="eyebrow">ВОПРОС {index + 1}</span><h1 ref={heading} tabIndex={-1}>{question.prompt}</h1><div className="quiz-answer-options">{question.options.map((option, i) => <button key={option.id} disabled={transitioning} onClick={() => { if (transitioning) return; setTransitioning(true); onAnswer(question.id, option.id); timer.current = setTimeout(() => setTransitioning(false), 200) }}><span>{['А', 'Б', 'В', 'Г'][i]}</span><strong>{option.text}</strong><ChevronRight size={17} /></button>)}</div></div><div className="quiz-scoring-note"><span><Sparkles size={17} />+{c.event.scoring.personalPerCorrect} тебе</span><span><Users size={17} />+{c.event.scoring.classPerCorrect} классу</span></div><p className="quiz-play-note">За каждый правильный ответ. Выбери один вариант — и сразу дальше.</p></div>
}

function Ranking({ controller: c, onInvite, onResults }: { controller: CompetitionController; onInvite: () => void; onResults: () => void }) {
  const [scope, setScope] = useState('school')
  const [group, setGroup] = useState('classes')
  const closed = c.attempt.phase === 'finished'
  const gap = nextClassGap(c.rankings, c.classId)
  return <><div className="page-heading ranking-page-heading"><div><span className="eyebrow">ОДНА ШКОЛА. МНОГО КОМАНД.</span><h1>Рейтинг</h1><p>{c.quiz.title} · {closed ? 'Итоги недели' : 'Битва этой недели'}</p></div><span className="page-symbol purple"><TrendingUp size={25} /></span></div><div className="competition-scope-tabs"><button className={scope === 'school' ? 'active' : ''} onClick={() => setScope('school')}>Моя школа</button><button className={scope === 'all' ? 'active' : ''} onClick={() => setScope('all')}>Все школы</button></div>{scope === 'all' ? <div className="card ranking-placeholder"><Empty title="Здесь будет больше своих">Межшкольный рейтинг появится позже. Сейчас в битве участвуют классы твоей школы.</Empty><button className="button secondary" onClick={() => setScope('school')}>К моей школе<ArrowLeft size={16} /></button></div> : <>
      {closed && <div className="competition-final-summary"><span className="eyebrow">ЭТА НЕДЕЛЯ ЗАВЕРШЕНА</span><h2>{c.mine.name} занял {c.mine.position} место</h2><div>{c.rankings.slice(0, 3).map((team, i) => <span key={team.classId}><small>{['🥇', '🥈', '🥉'][i]}</small><strong>{team.name}</strong><span>{team.points} очков</span></span>)}</div><p>{c.result ? `Личный результат: ${c.result.correct} / ${c.result.total} · ${c.result.personalPoints} очков` : 'Ты не проходил квиз этой недели. Увидимся в следующей битве.'}</p></div>}
      <div className="competition-group-tabs"><button className={group === 'classes' ? 'active' : ''} onClick={() => setGroup('classes')}><Users size={16} />Классы</button><button className={group === 'students' ? 'active' : ''} onClick={() => setGroup('students')}><Avatar size="small" />Ученики</button></div>
      <div className="card competition-ranking-list"><div className="ranking-list-heading"><span>{group === 'classes' ? 'КЛАСС' : `УЧЕНИК · ${c.mine.name}`}</span><span>ОЧКИ</span></div>{group === 'classes' ? c.rankings.map(team => <div key={team.classId} className={`ranking-row ${team.classId === c.classId ? 'mine' : ''}`} data-class-id={team.classId}><span className="ranking-position">{team.position}</span><span className="class-avatar">{team.name}</span><div><strong>{team.name}{team.classId === c.classId && <Tag>Твой класс</Tag>}</strong><small>{team.participants} из {team.members} участвуют</small></div><span className={`ranking-movement ${team.movement > 0 ? 'up' : team.movement < 0 ? 'down' : ''}`}>{team.movement > 0 ? <ArrowUpRight size={16} /> : team.movement < 0 ? <ArrowDownRight size={16} /> : '—'}{team.movement !== 0 && Math.abs(team.movement)}</span><strong className="ranking-points">{team.points}</strong></div>) : c.studentRankings.map(student => <div key={student.studentId} className={`ranking-row student-row ${student.studentId === DEMO_STUDENT_ID ? 'mine' : ''}`} data-student-id={student.studentId}><span className="ranking-position">{student.position}</span><Avatar person={student.studentId === DEMO_STUDENT_ID ? 'sasha' : student.studentId === 'anya' ? 'masha' : student.studentId === 'maxim' ? 'artem' : 'dasha'} /><div><strong>{student.studentId === DEMO_STUDENT_ID ? 'Ты' : student.name}{student.studentId === DEMO_STUDENT_ID && <Tag>Твой результат</Tag>}</strong><small>{student.studentId === DEMO_STUDENT_ID ? student.name : c.mine.name}</small></div><strong className="ranking-points">{student.points}</strong></div>)}</div>
      {!closed && <div className="ranking-team-progress"><div><strong>{gap ? `До ${gap.position} места — ${gap.points} очков` : 'Твой класс — на первой волне'}</strong><span>{c.mine.participants}/{c.mine.members}</span></div><div className="team-progress-track"><span style={{ width: `${c.mine.participants / c.mine.members * 100}%` }} /></div><p>{c.mine.members - c.mine.participants} ребят ещё могут помочь. Каждый верный ответ — вклад в общее дело.</p></div>}
      {!closed && <button className="button primary full competition-main-action" onClick={onInvite}><Users size={18} />Позвать одноклассников</button>}
      {c.result && <button className="button secondary full" onClick={onResults}>Мой результат<ArrowRight size={17} /></button>}
      {!c.result && !closed && <button className="button secondary full" onClick={onResults}>Пройти квиз<ArrowRight size={17} /></button>}
      <p className="competition-ranking-note">Очки и участники — демо-данные этой недели. Настоящей синхронизации пока нет.</p>
    </>}</>
}
