import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

let pageErrors: string[] = []
test.beforeEach(async ({ page }) => { pageErrors = []; page.on('pageerror', error => pageErrors.push(error.message)) })
test.afterEach(async () => { expect(pageErrors).toEqual([]) })

async function demo(page: Page) { await page.goto('/'); await page.getByRole('button', { name: 'Заглянуть в демо 9Б' }).click() }
async function nav(page: Page, label: string) { await expect(page.locator('.app-header')).toBeVisible(); const root = await page.locator('.desktop-nav').isVisible() ? '.desktop-nav' : '.bottom-nav'; await page.locator(root).getByRole('button', { name: new RegExp(`^${label}`) }).click() }
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy() }

test('onboarding: school search, class selection and profile survive reload', async ({ page }) => {
  await page.goto('/')
  await noOverflow(page)
  await page.getByRole('button', { name: 'Найти свой класс' }).click()
  await page.getByRole('textbox', { name: 'Найти школу' }).fill('нет такой школы')
  await expect(page.getByText('В демо доступны четыре школы.')).toBeVisible()
  await page.getByRole('textbox', { name: 'Найти школу' }).fill('57')
  await page.getByRole('button', { name: /Школа № 57/ }).click()
  await page.getByRole('button', { name: 'Дальше', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Погнали' })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Как тебя зовут?' }).fill('Алекс')
  await page.getByRole('button', { name: '9', exact: true }).click()
  await page.getByRole('button', { name: 'Б', exact: true }).click()
  await page.getByRole('button', { name: 'Погнали' }).click()
  await expect(page.getByRole('heading', { name: /Привет, Алекс/ })).toBeVisible()
  await noOverflow(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: /Привет, Алекс/ })).toBeVisible()
})

test('social actions: anonymous and school posts, likes, comments, saved posts', async ({ page }) => {
  await demo(page)
  await page.getByRole('button', { name: 'Что нового, Саша?' }).click()
  await page.getByRole('textbox', { name: 'Текст публикации' }).fill('Анонимная история для своих')
  await page.getByRole('switch', { name: 'Анонимная публикация' }).click()
  await page.getByRole('button', { name: 'Опубликовать' }).click()
  const post = page.locator('.post-card').filter({ hasText: 'Анонимная история для своих' })
  await expect(post.getByText('Кто-то из 9Б')).toBeVisible()
  await expect(post.getByText('Саша', { exact: true })).toHaveCount(0)
  await post.getByRole('button', { name: /^Нравится/ }).click()
  await expect(post.getByRole('button', { name: /^Убрать лайк/ })).toHaveAttribute('aria-pressed', 'true')
  await post.getByRole('button', { name: /^Комментарии/ }).click()
  await page.getByRole('textbox', { name: 'Комментарий', exact: true }).fill('Мы на одной волне!')
  await page.getByRole('button', { name: 'Отправить комментарий' }).click()
  await expect(page.getByText('Мы на одной волне!')).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
  await post.getByRole('button', { name: 'Сохранить публикацию' }).click()
  await nav(page, 'Профиль')
  await page.getByRole('button', { name: /^Мои сохранённые/ }).click()
  await expect(page.getByText('Анонимная история для своих')).toBeVisible()
  await page.getByRole('button', { name: 'Вернуться в ленту' }).click()
  await page.getByRole('button', { name: 'Что нового, Саша?' }).click()
  await page.getByRole('textbox', { name: 'Текст публикации' }).fill('Школьная новость от Саши')
  await page.getByRole('combobox', { name: 'Кому видна публикация' }).selectOption('school')
  await page.getByRole('button', { name: 'Опубликовать' }).click()
  await expect(page.locator('.post-card').filter({ hasText: 'Школьная новость от Саши' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Вся школа', exact: true }).click()
  await expect(page.getByText('Школьная новость от Саши')).toBeVisible()
  await noOverflow(page)
})

test('study: weekly photo import, manual homework and photo homework review', async ({ page }) => {
  await demo(page)
  await nav(page, 'Учёба')
  await page.getByRole('tab', { name: 'Расписание', exact: true }).click()
  await page.getByRole('button', { name: 'Загрузить расписание по фото' }).click()
  await page.getByRole('button', { name: 'Попробовать на демо-фото' }).click()
  await expect(page.getByRole('heading', { name: 'Проверь расписание' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Кабинет 1', exact: true }).fill('999')
  await page.getByRole('button', { name: 'Сохранить неделю' }).click()
  await expect(page.locator('main').getByText('Каб. 999', { exact: false })).toBeVisible()
  await page.getByRole('tab', { name: 'Домашка', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить', exact: true }).click()
  await page.getByLabel('Предмет', { exact: true }).selectOption('Биология')
  await page.getByRole('textbox', { name: 'Что задали?' }).fill('Подготовить схему клетки')
  await page.getByRole('button', { name: 'Добавить задание' }).click()
  const manual = page.locator('.homework-item').filter({ hasText: 'Подготовить схему клетки' })
  await expect(manual).toBeVisible()
  await manual.getByRole('button', { name: 'Завершить: Биология' }).click()
  await page.getByRole('button', { name: /^Готово/ }).click()
  await expect(page.getByText('Подготовить схему клетки')).toBeVisible()
  await page.getByRole('button', { name: 'Добавить', exact: true }).click()
  await page.getByRole('button', { name: 'По фотографии', exact: true }).click()
  await page.getByRole('button', { name: 'Попробовать на демо-фото' }).click()
  await expect(page.getByRole('textbox', { name: 'Что задали?' })).toHaveValue('№ 112, 114. Повторить признаки подобия треугольников')
  await page.getByRole('textbox', { name: 'Что задали?' }).fill('Проверенная домашка по фото')
  await page.getByRole('button', { name: 'Добавить задание' }).click()
  await page.getByRole('button', { name: /^Сделать/ }).click()
  await expect(page.getByText('Проверенная домашка по фото')).toBeVisible()
  await page.reload()
  await nav(page, 'Учёба')
  await page.getByRole('tab', { name: 'Расписание', exact: true }).click()
  await expect(page.locator('main').getByText('Каб. 999', { exact: false })).toBeVisible()
  await noOverflow(page)
})

test('AI demos, notifications and profile editing', async ({ page }) => {
  await demo(page)
  await nav(page, 'Учёба')
  await page.getByRole('button', { name: 'Читать утренний дайджест' }).click()
  await expect(page.getByRole('heading', { name: 'Хороший день начинается с тебя.' })).toBeVisible()
  await page.getByRole('button', { name: 'Вечер', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ты сегодня многое успел.' })).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
  await page.getByRole('tab', { name: 'AI-репетитор' }).click()
  await page.getByRole('button', { name: 'Квадратные уравнения', exact: true }).click()
  await expect(page.getByText(/Давай разберём на примере/)).toBeVisible()
  await page.getByRole('textbox', { name: 'Вопрос AI-репетитору' }).fill('Расскажи о динозаврах')
  await page.getByRole('button', { name: 'Отправить вопрос' }).click()
  await expect(page.getByText(/Это демо-репетитор/)).toBeVisible()
  await nav(page, 'Уведомления')
  await page.getByRole('button', { name: 'Прочитать все' }).click()
  await page.getByRole('button', { name: /^Новые/ }).click()
  await expect(page.getByRole('heading', { name: 'Всё прочитано' })).toBeVisible()
  await nav(page, 'Профиль')
  await page.getByRole('button', { name: 'Редактировать' }).click()
  await page.getByRole('textbox', { name: 'Твоё имя' }).fill('Миша')
  await page.getByRole('textbox', { name: 'Пара слов о себе' }).fill('Люблю космос и гитару')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Миша', exact: true })).toBeVisible()
  await expect(page.getByText('Люблю космос и гитару')).toBeVisible()
  await noOverflow(page)
})

test('visual previews and narrow-screen layout', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.screenshot({ path: `artifacts/onboarding-${testInfo.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Заглянуть в демо 9Б' }).click()
  await page.screenshot({ path: `artifacts/feed-${testInfo.project.name}.png`, fullPage: true })
  await nav(page, 'Учёба')
  await page.screenshot({ path: `artifacts/study-${testInfo.project.name}.png`, fullPage: true })
  await page.setViewportSize({ width: 320, height: 740 })
  await noOverflow(page)
  await nav(page, 'Лента')
  await noOverflow(page)
  await nav(page, 'Уведомления')
  await noOverflow(page)
  await nav(page, 'Профиль')
  await noOverflow(page)
})

test('local photo upload, keyboard dialog dismissal and reviewed result', async ({ page }) => {
  await demo(page)
  await nav(page, 'Учёба')
  await page.getByRole('tab', { name: 'Домашка', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Добавить', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Добавить', exact: true }).click()
  await page.getByRole('button', { name: 'По фотографии', exact: true }).click()
  await page.getByLabel('Выбрать фотографию', { exact: true }).setInputFiles('public/logo-reference.png')
  await expect(page.getByAltText('Выбранное фото для демо-распознавания')).toBeVisible()
  await page.getByRole('button', { name: 'Распознать пример', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Что задали?' })).toHaveValue('№ 112, 114. Повторить признаки подобия треугольников')
  await page.getByRole('button', { name: 'Добавить задание' }).click()
  await expect(page.locator('.homework-item').filter({ hasText: '№ 112, 114.' })).toBeVisible()
})

test('poll creation, unique options, switching and cancelling a persisted vote', async ({ page }) => {
  await demo(page)
  await page.getByRole('button', { name: 'Создать', exact: true }).click()
  await page.getByRole('button', { name: /^Опрос Узнай/ }).click()
  await page.getByRole('textbox', { name: 'Что спросим у ребят?' }).fill('Что берём на пикник?')
  await page.getByRole('textbox', { name: 'Вариант 1', exact: true }).fill('Какао')
  await page.getByRole('textbox', { name: 'Вариант 2', exact: true }).fill('Какао')
  await expect(page.getByRole('button', { name: 'Опубликовать опрос', exact: true })).toBeDisabled()
  await expect(page.getByText('Варианты должны отличаться друг от друга.')).toBeVisible()
  await page.getByRole('textbox', { name: 'Вариант 2', exact: true }).fill('Печенье')
  await page.getByRole('button', { name: 'Добавить вариант', exact: true }).click()
  await page.getByRole('textbox', { name: 'Вариант 3', exact: true }).fill('Пледы')
  await page.getByRole('button', { name: 'Опубликовать опрос', exact: true }).click()
  const poll = page.getByRole('region', { name: 'Опрос: Что берём на пикник?' })
  await poll.getByRole('button', { name: 'Какао', exact: true }).click()
  await expect(poll.getByRole('button', { name: /Какао/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(poll.getByText('1 голос', { exact: true })).toBeVisible()
  await poll.getByRole('button', { name: /Печенье/ }).click()
  await expect(poll.getByRole('button', { name: /Какао/ })).toHaveAttribute('aria-pressed', 'false')
  await expect(poll.getByText('1 голос', { exact: true })).toBeVisible()
  await page.reload()
  await expect(poll.getByRole('button', { name: /Печенье/ })).toHaveAttribute('aria-pressed', 'true')
  await poll.getByRole('button', { name: 'Отменить голос' }).click()
  await expect(poll.getByText('0 голосов', { exact: true })).toBeVisible()
})

test('reactions switch without double counting and survive reload', async ({ page }) => {
  await demo(page)
  const post = page.locator('.post-card').filter({ hasText: 'Ребят, в пятницу' })
  await post.getByRole('button', { name: /^Выбрать реакцию/ }).click()
  await post.getByRole('group', { name: 'Реакции', exact: true }).getByRole('button', { name: 'Огонь', exact: true }).click()
  await expect(post.getByRole('button', { name: /^Убрать реакцию Огонь/ })).toHaveAttribute('aria-pressed', 'true')
  await post.getByRole('button', { name: /^Выбрать реакцию/ }).click()
  await post.getByRole('group', { name: 'Реакции', exact: true }).getByRole('button', { name: 'Поддерживаю', exact: true }).click()
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('mayak-posts-v1')!).find((p: { id: string }) => p.id === 'p1'))
  expect(stored.reactions.fire).toBe(0)
  expect(stored.reactions.support).toBe(1)
  expect(stored.reactions.heart).toBe(18)
  await page.reload()
  await expect(post.getByRole('button', { name: /^Убрать реакцию Поддерживаю/ })).toHaveAttribute('aria-pressed', 'true')
  await post.getByRole('button', { name: /^Убрать реакцию Поддерживаю/ }).click()
  await expect(post.getByRole('button', { name: /^Нравится/ })).toHaveAttribute('aria-pressed', 'false')
})

test('photo attachments validate, preview, remove and persist with gallery viewing', async ({ page }) => {
  await demo(page)
  await page.getByRole('button', { name: 'Что нового, Саша?' }).click()
  await page.getByLabel('Фотографии для публикации').setInputFiles({ name: 'document.txt', mimeType: 'text/plain', buffer: Buffer.from('not an image') })
  await expect(page.getByText('Выбери фото JPG, PNG или WebP.')).toBeVisible()
  await page.getByLabel('Фотографии для публикации').setInputFiles(['public/logo-reference.png', 'public/logo-reference.png'])
  await expect(page.getByAltText('Прикреплённая фотография 2')).toBeVisible()
  await page.getByRole('button', { name: 'Удалить фотографию 2', exact: true }).click()
  await expect(page.getByAltText('Прикреплённая фотография 2')).toHaveCount(0)
  await page.getByLabel('Фотографии для публикации').setInputFiles('public/logo-reference.png')
  await expect(page.getByAltText('Прикреплённая фотография 2')).toBeVisible()
  await page.getByRole('textbox', { name: 'Текст публикации' }).fill('Наши фотографии после уроков')
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click()
  const post = page.locator('.post-card').filter({ hasText: 'Наши фотографии после уроков' })
  await expect(post.locator('.post-photo-grid img')).toHaveCount(2)
  await post.getByRole('button', { name: 'Открыть фотографию 1', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Фото 1 из 2' })).toBeVisible()
  await page.getByRole('button', { name: 'Следующая фотография' }).click()
  await expect(page.getByRole('dialog', { name: 'Фото 2 из 2' })).toBeVisible()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('dialog', { name: 'Фото 1 из 2' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(post.locator('.post-photo-grid img')).toHaveCount(2)
  await expect(post.locator('.post-photo-grid img').first()).toHaveAttribute('src', /^data:image\/jpeg;base64,/)
})

test('navigation keeps the selected feed, schedule day and scroll position', async ({ page }) => {
  await demo(page)
  await page.getByRole('button', { name: 'Вся школа', exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 250))
  await nav(page, 'Учёба')
  await page.getByRole('tab', { name: 'Расписание', exact: true }).click()
  await page.getByRole('button', { name: /^Чт\s*1$/ }).click()
  await nav(page, 'Профиль')
  await nav(page, 'Учёба')
  await expect(page.getByRole('tab', { name: 'Расписание', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: /^Чт\s*1$/ })).toHaveAttribute('aria-pressed', 'true')
  await nav(page, 'Лента')
  await expect(page.getByRole('button', { name: 'Вся школа', exact: true })).toHaveClass('active')
  await expect.poll(async () => page.evaluate(() => window.scrollY)).toBe(250)
})

test('upgrade preserves existing demo data and full storage keeps a draft editable', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('mayak-onboarded-v1', 'true')
    localStorage.setItem('mayak-posts-v1', JSON.stringify([{ id: 'old-user-post', author: 'Саша', avatar: 'sasha', color: 'purple', time: 'Вчера', scope: 'class', text: 'Моя история до обновления', likes: 7, liked: true, saved: true, comments: [] }]))
  })
  await page.goto('/')
  await expect(page.getByText('Моя история до обновления')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Как проведём пятницу после уроков?' })).toBeVisible()
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key: string, value: string) { if (key === 'mayak-posts-v1') throw new DOMException('Full', 'QuotaExceededError'); return original.call(this, key, value) }
  })
  await page.getByRole('button', { name: 'Что нового, Саша?' }).click()
  await page.getByRole('textbox', { name: 'Текст публикации' }).fill('Черновик не должен потеряться')
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Браузер не смог сохранить пост')
  await expect(page.getByRole('textbox', { name: 'Текст публикации' })).toHaveValue('Черновик не должен потеряться')
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
  await expect(page.getByText('Моя история до обновления')).toBeVisible()
})

test('outline icons stay uniform and local stickers can be previewed, removed and published', async ({ page }, testInfo) => {
  await demo(page)
  const iconViolations = async () => page.locator('svg.mayak-icon').evaluateAll(icons => icons.filter(icon => {
    if (!icon.getClientRects().length) return false
    const style = getComputedStyle(icon)
    return style.width !== '24px' || style.height !== '24px' || style.strokeWidth !== '2.5px' || style.fill !== 'none' || style.strokeLinecap !== 'round' || style.strokeLinejoin !== 'round'
  }).map(icon => icon.getAttribute('class')))
  expect(await iconViolations()).toEqual([])
  await expect(page.locator('svg.lucide:not(.mayak-icon)')).toHaveCount(0)
  await page.getByRole('button', { name: 'Что нового, Саша?' }).click()
  await page.getByRole('button', { name: 'Стикеры', exact: true }).click()
  const picker = page.getByRole('group', { name: 'Стикеры Маяка', exact: true })
  await expect(picker.getByRole('button')).toHaveCount(22)
  await expect.poll(() => picker.locator('img').evaluateAll(images => images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
  await picker.getByRole('button', { name: 'Стикер: В цель', exact: true }).click()
  await expect(page.locator('.composer-sticker-preview').getByRole('img', { name: 'В цель', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Убрать стикер', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Опубликовать', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Стикеры', exact: true }).click()
  await picker.getByRole('button', { name: 'Стикер: В цель', exact: true }).click()
  await page.screenshot({ path: `artifacts/sticker-composer-${testInfo.project.name}.png` })
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click()
  const post = page.locator('.post-card').filter({ has: page.locator('[data-sticker="goal"]') })
  await expect(post.getByRole('img', { name: 'В цель', exact: true })).toBeVisible()
  await post.getByRole('button', { name: /^Нравится/ }).click()
  await post.getByRole('button', { name: 'Сохранить публикацию', exact: true }).click()
  expect(await iconViolations()).toEqual([])
  await page.reload()
  await expect(post.getByRole('img', { name: 'В цель', exact: true })).toBeVisible()
  await nav(page, 'Учёба')
  expect(await iconViolations()).toEqual([])
  await page.setViewportSize({ width: 320, height: 740 })
  await noOverflow(page)
  await nav(page, 'Профиль')
  await noOverflow(page)
  expect(await iconViolations()).toEqual([])
})
