import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { knowledgeQuiz, weeklyCompetition, initialClassRankings } from '../src/features/competition/mock'
import { applyClassContribution, gradeQuiz, nextClassGap, rankClasses } from '../src/features/competition/logic'

async function demo(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Заглянуть в демо 9Б' }).click()
}
async function answer(page: Page, index: number, correct = true) {
  const question = knowledgeQuiz.questions[index]
  await expect(page.getByRole('progressbar', { name: 'Прогресс квиза' })).toHaveAttribute('aria-valuenow', String(index + 1))
  const option = question.options.find(o => correct ? o.id === question.correctOptionId : o.id !== question.correctOptionId)!
  await page.locator('.quiz-answer-options').getByRole('button', { name: new RegExp(option.text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')) }).click()
}
async function complete(page: Page, correctCount = 8) {
  await page.getByRole('button', { name: 'Пройти квиз', exact: true }).click()
  for (let i = 0; i < knowledgeQuiz.questions.length; i++) await answer(page, i, i < correctCount)
  await expect(page.getByText('КВИЗ ПРОЙДЕН', { exact: true })).toBeVisible()
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
}

test('quiz: real score, class movement, personal ranking and a single school post survive reload', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await demo(page)
  const card = page.getByRole('region', { name: 'Еженедельный квиз' })
  await expect(card.getByText('4 место', { exact: true })).toBeVisible()
  await page.screenshot({ path: `artifacts/competition-entry-${testInfo.project.name}.png` })
  await complete(page)
  await expect(page.locator('.quiz-result-score')).toHaveText('8из 10')
  await expect(page.locator('.quiz-score-cards')).toContainText('800очков')
  await expect(page.locator('.quiz-score-cards')).toContainText('+8очков')
  await expect(page.getByText('9Б поднялся с 4-го на 3-е место', { exact: true })).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: `artifacts/quiz-result-${testInfo.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Поделиться результатом', exact: true }).click()
  await expect(page.getByLabel('Текст для своих')).toHaveValue(/8 из 10/)
  await expect(page.getByText('Демо-карточка для обмена. Системная отправка пока не подключена.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Посмотреть рейтинг', exact: true }).click()
  await expect(page.locator('[data-class-id="class-9b"]')).toHaveClass(/mine/)
  await expect(page.locator('[data-class-id="class-9b"] .ranking-points')).toHaveText('165')
  await expect(page.locator('.ranking-team-progress').getByText('До 2 места — 6 очков', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Позвать одноклассников', exact: true }).click()
  await expect(page.getByLabel('Текст для своих')).toHaveValue(/поможем 9Б подняться выше/)
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `artifacts/quiz-ranking-${testInfo.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Ученики', exact: true }).click()
  await expect(page.locator('[data-student-id="current-student"] .ranking-points')).toHaveText('800')
  await expect(page.locator('[data-student-id="current-student"] .ranking-position')).toHaveText('3')
  await page.getByRole('button', { name: 'Все школы', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Здесь будет больше своих' })).toBeVisible()
  await expect(page.locator('.ranking-row')).toHaveCount(0)
  await page.getByRole('button', { name: 'К моей школе', exact: true }).click()
  await page.getByRole('button', { name: 'К ленте', exact: true }).click()
  await expect(card.getByRole('button', { name: 'Посмотреть результаты', exact: true })).toBeVisible()
  await expect(card.getByText('3 место', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Вся школа', exact: true }).click()
  const systemPost = page.locator('.competition-system-post').filter({ hasText: '9Б поднялся на 3 место' })
  await expect(systemPost).toHaveCount(1)
  await expect(systemPost).toContainText('До 8Б осталось всего 6 очков.')
  await systemPost.getByRole('button', { name: 'Участвовать', exact: true }).click()
  await expect(page.locator('.quiz-result-score')).toHaveText('8из 10')
  await page.reload()
  await card.getByRole('button', { name: 'Посмотреть результаты', exact: true }).click()
  await page.getByRole('button', { name: 'Посмотреть рейтинг', exact: true }).click()
  await expect(page.locator('[data-class-id="class-9b"] .ranking-points')).toHaveText('165')
  const storedPosts = await page.evaluate(() => JSON.parse(localStorage.getItem('mayak-posts-v1')!).filter((p: { id: string }) => p.id.endsWith('-result-current-student')))
  expect(storedPosts).toHaveLength(1)
  await page.getByRole('button', { name: 'Демо события', exact: true }).click()
  await page.getByRole('button', { name: /^Квиз завершён Итоги/ }).click()
  await expect(page.locator('.competition-final-summary')).toContainText('Личный результат: 8 / 10 · 800 очков')
  await page.getByRole('button', { name: 'К ленте', exact: true }).click()
  await expect(card).toContainText('9Б занял 2 место')
  await expect(card).toContainText('Твой результат: 8 / 10')
  await expect(card.getByRole('button', { name: 'Квиз завершён', exact: true })).toBeDisabled()
  expect(errors).toEqual([])
})

test('quiz: interruption resumes the next question; closing the event prevents new answers', async ({ page }, testInfo) => {
  await demo(page)
  await page.getByRole('button', { name: 'Пройти квиз', exact: true }).click()
  for (let i = 0; i < 3; i++) await answer(page, i)
  await page.reload()
  await page.getByRole('button', { name: 'Продолжить квиз', exact: true }).click()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '4')
  await page.screenshot({ path: `artifacts/quiz-question-${testInfo.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Демо события', exact: true }).click()
  await page.getByRole('button', { name: /^Последние сутки/ }).click()
  await page.getByRole('button', { name: 'К ленте', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Еженедельный квиз' })).toContainText('До конца: 24 часа')
  await page.getByRole('button', { name: 'Вся школа', exact: true }).click()
  await expect(page.locator('.post-card').filter({ hasText: 'До конца квиза осталось 24 часа' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Продолжить квиз', exact: true }).click()
  await page.getByRole('button', { name: 'Демо события', exact: true }).click()
  await page.getByRole('button', { name: /^Квиз завершён Итоги/ }).click()
  await expect(page.locator('.competition-final-summary')).toContainText('9Б занял 2 место')
  await expect(page.locator('.competition-final-summary')).toContainText('Ты не проходил квиз этой недели')
  await expect(page.getByRole('button', { name: 'Пройти квиз', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 320, height: 740 })
  await noOverflow(page)
  await page.getByRole('button', { name: 'К ленте', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Квиз завершён', exact: true })).toBeDisabled()
  await noOverflow(page)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Квиз завершён', exact: true })).toBeDisabled()
  const attempt = await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('mayak-competitions-v1')!))[0])
  expect(attempt).toMatchObject({ phase: 'finished', result: null, answers: [{}, {}, {}] })
})

test('quiz: final podium keeps the actual personal result and zero answers never earn points', async ({ page }) => {
  await demo(page)
  await complete(page, 0)
  await expect(page.locator('.quiz-result-score')).toHaveText('0из 10')
  await expect(page.locator('.quiz-score-cards')).toContainText('+0очков')
  await page.getByRole('button', { name: 'Демо события', exact: true }).click()
  await page.getByRole('button', { name: /^Квиз завершён Итоги/ }).click()
  await expect(page.locator('.competition-final-summary')).toContainText('Личный результат: 0 / 10 · 0 очков')
  await expect(page.locator('.competition-final-summary > div > span > strong')).toHaveText(['10А', '9Б', '8Б'])
  await expect(page.getByRole('button', { name: 'Позвать одноклассников', exact: true })).toHaveCount(0)
  await noOverflow(page)
})

test('scoring uses event rules and unique valid answers; ties and contributions remain stable', () => {
  const answers = knowledgeQuiz.questions.slice(0, 8).map(q => ({ questionId: q.id, optionId: q.correctOptionId }))
  const result = gradeQuiz(knowledgeQuiz, weeklyCompetition, [...answers, answers[0], { questionId: 'missing', optionId: 'a' }], initialClassRankings, 'class-9b', 'test')
  expect(result).toMatchObject({ correct: 8, personalPoints: 800, classPoints: 8, positionBefore: 4, positionAfter: 3 })
  expect(result.answers).toHaveLength(8)
  const once = applyClassContribution(initialClassRankings, result)
  expect(applyClassContribution(initialClassRankings, result)).toEqual(once)
  expect(nextClassGap(rankClasses(once), 'class-9b')).toMatchObject({ className: '8Б', points: 6, position: 2 })
  expect(initialClassRankings.find(c => c.classId === 'class-9b')?.points).toBe(157)
  const otherRules = gradeQuiz({ ...knowledgeQuiz, id: 'another-quiz', questions: knowledgeQuiz.questions.slice(0, 2) }, { ...weeklyCompetition, id: 'another-event', scoring: { personalPerCorrect: 25, classPerCorrect: 2 } }, answers, initialClassRankings, 'class-9b', 'test')
  expect(otherRules).toMatchObject({ total: 2, correct: 2, personalPoints: 50, classPoints: 4, positionAfter: 3 })
  const tied = rankClasses(initialClassRankings.map(c => c.classId === 'class-9b' ? { ...c, points: 161 } : c))
  expect(tied.filter(c => c.points === 161).map(c => c.position)).toEqual([3, 3])
})

test('another selected class starts at zero and receives only its own contribution', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Заглянуть в демо 9Б' })).toBeVisible()
  await page.evaluate(() => {
    const profile = JSON.parse(localStorage.getItem('mayak-profile-v1')!)
    localStorage.setItem('mayak-onboarded-v1', 'true')
    localStorage.setItem('mayak-profile-v1', JSON.stringify({ ...profile, className: '7А' }))
  })
  await page.reload()
  await expect(page.getByRole('region', { name: 'Еженедельный квиз' })).toContainText('7А')
  await complete(page, 2)
  await expect(page.locator('.quiz-result-score')).toHaveText('2из 10')
  await page.getByRole('button', { name: 'Посмотреть рейтинг', exact: true }).click()
  await expect(page.locator('[data-class-id="class-7А"] .ranking-points')).toHaveText('2')
  await expect(page.locator('[data-class-id="class-9b"] .ranking-points')).toHaveText('157')
  await page.getByRole('button', { name: 'Ученики', exact: true }).click()
  await expect(page.locator('.student-row')).toHaveCount(1)
  await expect(page.locator('[data-student-id="current-student"] .ranking-points')).toHaveText('200')
})
