import { expect, test, type Page } from '@playwright/test'

async function demo(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Заглянуть в демо 9Б', exact: true }).click()
}
async function compose(page: Page) { await page.getByRole('button', { name: 'Что нового, Саша?', exact: true }).click() }

test('complete publication draft survives closing and reload, and clears after publishing', async ({ page }, testInfo) => {
  await demo(page)
  await compose(page)
  await page.getByRole('button', { name: 'Опрос', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст публикации' }).fill('Собираемся после уроков')
  await page.getByRole('textbox', { name: 'Что спросим у ребят?' }).fill('Что возьмём с собой?')
  await page.getByRole('textbox', { name: 'Вариант 1', exact: true }).fill('Чай')
  await page.getByRole('textbox', { name: 'Вариант 2', exact: true }).fill('Какао')
  await page.getByRole('combobox', { name: 'Кому видна публикация' }).selectOption('school')
  await page.getByRole('switch', { name: 'Анонимная публикация' }).click()
  await page.getByLabel('Фотографии для публикации', { exact: true }).setInputFiles('public/logo-reference.png')
  await expect(page.getByAltText('Прикреплённая фотография 1')).toBeVisible()
  await page.getByRole('button', { name: 'Стикеры', exact: true }).click()
  await page.getByRole('button', { name: 'Стикер: В цель', exact: true }).click()
  await expect(page.getByText('Черновик сохранён на этом устройстве', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await compose(page)
  await expect(page.getByText('Черновик восстановлен', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Что спросим у ребят?' })).toHaveValue('Что возьмём с собой?')
  await page.reload()
  await compose(page)
  await expect(page.getByRole('textbox', { name: 'Текст публикации' })).toHaveValue('Собираемся после уроков')
  await expect(page.getByRole('textbox', { name: 'Вариант 2', exact: true })).toHaveValue('Какао')
  await expect(page.getByRole('combobox', { name: 'Кому видна публикация' })).toHaveValue('school')
  await expect(page.getByRole('switch', { name: 'Анонимная публикация' })).toBeChecked()
  await expect(page.getByAltText('Прикреплённая фотография 1')).toBeVisible()
  await expect(page.locator('.composer-sticker-preview img')).toBeVisible()
  await page.screenshot({ path: `artifacts/consumer-draft-${testInfo.project.name}.png`, animations: 'disabled' })
  await page.getByRole('button', { name: 'Опубликовать опрос', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Опрос: Что возьмём с собой?' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('mayak-post-draft-v1'))).toBeNull()
  await compose(page)
  await expect(page.getByRole('textbox', { name: 'Текст публикации' })).toHaveValue('')
  await expect(page.locator('.composer-photos img, .composer-sticker-preview img')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Текст публикации' }).fill('Удалить этот черновик')
  await page.getByRole('button', { name: 'Очистить черновик', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Текст публикации' })).toHaveValue('')
  expect(await page.evaluate(() => localStorage.getItem('mayak-post-draft-v1'))).toBeNull()
  await page.keyboard.press('Escape')
  await compose(page)
  await expect(page.getByRole('button', { name: 'Опубликовать', exact: true })).toBeDisabled()
})

test('feed sorting works and persists; closing search removes the hidden filter', async ({ page }) => {
  await demo(page)
  const first = page.locator('.post-card').first()
  await expect(first.locator('.post-author strong')).toHaveText('Маша Волкова')
  await page.getByRole('button', { name: 'Порядок публикаций: Свежее', exact: true }).click()
  await page.getByRole('button', { name: /^Популярное Сначала/ }).click()
  await expect(first.locator('.post-author strong')).toHaveText('Кто-то из 9Б')
  await page.getByRole('button', { name: 'Порядок публикаций: Популярное', exact: true }).click()
  await page.getByRole('button', { name: /^Обсуждаемое Сначала/ }).click()
  await expect(first.locator('.post-author strong')).toHaveText('Маша Волкова')
  await page.getByRole('button', { name: 'Поиск по ленте', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст поиска' }).fill('уравнения')
  await expect(page.locator('.post-card')).toHaveCount(1)
  await expect(page.getByText('1 публикация по твоему запросу', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Поиск по ленте', exact: true })).toBeFocused()
  await expect(page.locator('.post-card')).toHaveCount(4)
  await page.getByRole('button', { name: 'Поиск по ленте', exact: true }).click()
  await page.getByRole('textbox', { name: 'Текст поиска' }).fill('несуществующий пост')
  await expect(page.locator('.post-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Поиск по ленте', exact: true }).click()
  await expect(page.locator('.post-card')).toHaveCount(4)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Порядок публикаций: Обсуждаемое', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Порядок публикаций: Обсуждаемое', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Порядок публикаций', exact: true })).toBeVisible()
})

test('long comment threads keep the input visible and scroll to newly sent replies', async ({ page }, testInfo) => {
  await demo(page)
  await page.evaluate(() => {
    const posts = JSON.parse(localStorage.getItem('mayak-posts-v1')!)
    const post = posts.find((item: { id: string }) => item.id === 'p1')
    post.comments = Array.from({ length: 24 }, (_, index) => ({ id: `thread-${index}`, author: 'Маша', avatar: 'masha', text: `Сообщение ${index + 1}: увидимся после уроков у входа в парк` }))
    localStorage.setItem('mayak-posts-v1', JSON.stringify(posts))
  })
  await page.reload()
  await page.locator('.post-card').first().getByRole('button', { name: /^Комментарии/ }).click()
  const input = page.getByRole('textbox', { name: 'Комментарий', exact: true })
  const list = page.locator('.comments-sheet .comments-list')
  await expect(input).toBeVisible()
  expect(await list.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
  await expect(page.getByText(/^Сообщение 24:/)).toBeInViewport()
  await page.setViewportSize({ width: 320, height: 480 })
  await expect(input).toBeInViewport()
  await expect(input).toHaveCSS('font-size', '16px')
  await input.fill('Мой новый ответ в длинной ветке')
  await page.getByRole('button', { name: 'Отправить комментарий', exact: true }).click()
  await expect(page.getByText('Мой новый ответ в длинной ветке', { exact: true })).toBeInViewport()
  await expect(input).toHaveValue('')
  await page.screenshot({ path: `artifacts/consumer-comments-${testInfo.project.name}.png`, animations: 'disabled' })
  await page.keyboard.press('Escape')
  await compose(page)
  await page.getByRole('button', { name: 'Опрос', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Вариант 1', exact: true })).toHaveCSS('font-size', '16px')
  await expect(page.getByRole('combobox', { name: 'Кому видна публикация' })).toHaveCSS('font-size', '16px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
