import { expect, test, type Page } from '@playwright/test'
test.setTimeout(60000)

async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy() }
async function fitsViewport(page: Page) {
  const card = page.locator('.ml-game-card')
  const bounds = await card.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.y).toBeGreaterThanOrEqual(70)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(await page.evaluate(() => innerHeight))
}
async function lightLighthouse(page: Page, checkFit = false) {
  const initialUrl = page.url()
  await page.getByRole('button', { name: 'Зажечь маяк', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Какую планету/ })).toBeFocused()
  if (checkFit) await fitsViewport(page)
  await page.getByRole('button', { name: /Венера/ }).click()
  await expect(page.getByRole('status')).toContainText('Попробуй ещё', { ignoreCase: true })
  await expect(page.getByLabel('0 / 3 искры')).toBeVisible()
  await page.getByRole('button', { name: /Марс/ }).click()
  await expect(page.getByLabel('1 / 3 искры')).toBeVisible()
  await expect(page.locator('.ml-main-beacon .lighthouse-window-one')).toHaveCSS('opacity', '0.9')
  await expect(page.getByRole('heading', { name: 'Поймай 3 звезды' })).toBeFocused()
  if (checkFit) await fitsViewport(page)
  const positions = []
  for (let index = 1; index <= 3; index++) {
    const star = page.getByRole('button', { name: `Поймать звезду ${index}` })
    await expect(star).not.toHaveClass(/is-caught/)
    const target = (await star.boundingBox())!
    const arena = (await page.locator('.ml-star-arena').boundingBox())!
    expect(target.width).toBeGreaterThanOrEqual(44)
    expect(target.height).toBeGreaterThanOrEqual(44)
    expect(target.x - arena.x).toBeGreaterThanOrEqual(7)
    expect(target.y - arena.y).toBeGreaterThanOrEqual(7)
    expect(arena.x + arena.width - target.x - target.width).toBeGreaterThanOrEqual(7)
    expect(arena.y + arena.height - target.y - target.height).toBeGreaterThanOrEqual(7)
    positions.push(await star.getAttribute('style'))
    await star.click()
    await expect(page.locator('.ml-star-count')).toHaveText(`${index} / 3`)
  }
  expect(new Set(positions).size).toBeGreaterThan(1)
  await expect(page.getByRole('heading', { name: 'Что зажигает твой интерес?' })).toBeFocused()
  if (checkFit) await fitsViewport(page)
  await expect(page.getByLabel('2 / 3 искры')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Готово', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: /Квизы Узнавать/ }).click()
  await page.getByRole('button', { name: /Творчество Выражать/ }).click()
  await expect(page.getByRole('button', { name: /Квизы Узнавать/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /Творчество Выражать/ }).click()
  await expect(page.getByRole('button', { name: /Творчество Выражать/ })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Маяк зажжён!' })).toBeFocused()
  if (checkFit) await fitsViewport(page)
  await expect(page.getByTestId('lighthouse')).toHaveAttribute('data-sparks', '3')
  await expect(page.getByLabel('3 / 3 искры')).toBeVisible()
  await expect(page.locator('.ml-earned')).toContainText('+30')
  await expect(page.locator('.ml-profile-preview')).toContainText('Новичок')
  await expect(page.locator('.ml-main-beacon .lighthouse-beam')).toHaveCSS('opacity', '1')
  expect(page.url()).toBe(initialUrl)
}
async function registerProfile(page: Page) {
  await page.getByLabel('Имя', { exact: true }).fill('Искра')
  await page.getByLabel('Email', { exact: true }).fill('student@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('demo-password-123')
  await page.getByRole('button', { name: 'Показать пароль' }).click()
  await expect(page.getByLabel('Пароль', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Скрыть пароль' }).click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByLabel('День', { exact: true }).selectOption('12')
  await page.getByLabel('Месяц', { exact: true }).selectOption('4')
  await page.getByLabel('Год', { exact: true }).selectOption('2009')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await page.getByRole('textbox', { name: 'Найти школу' }).fill('123')
  await page.getByRole('button', { name: /ГБОУ школа №123/ }).click()
  await page.getByRole('button', { name: 'Это моя школа', exact: true }).click()
  await page.getByRole('button', { name: '9', exact: true }).click()
  await page.getByRole('button', { name: 'Б', exact: true }).click()
  await page.getByRole('button', { name: 'Присоединиться к 9Б', exact: true }).click()
  await page.getByLabel('Username', { exact: true }).fill('iskra_first')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await page.getByRole('checkbox', { name: /Я принимаю/ }).check()
  await page.getByRole('button', { name: 'Войти в Маяк', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Добро пожаловать в 9Б' })).toBeVisible()
  await page.getByRole('button', { name: 'Перейти в ленту', exact: true }).click()
}
test('landing: three games, shared profile card and registration into the app', async ({ page }) => {
  const errors: string[] = []
  const backendRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/\/(auth|users|schools|classes)(\/|\?)/.test(request.url())) backendRequests.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Зажги свой/ })).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: `artifacts/landing-hero-${test.info().project.name}.png`, animations: 'disabled' })
  await lightLighthouse(page)
  await page.screenshot({ path: `artifacts/landing-completed-${test.info().project.name}.png`, animations: 'disabled' })
  await page.getByRole('link', { name: 'Создать профиль', exact: true }).click()
  await expect(page).toHaveURL(/\/register$/)
  await expect(page.getByTestId('intro-reward')).toContainText('+30 очков')
  await page.screenshot({ path: `artifacts/landing-register-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' })
  await registerProfile(page)
  await expect(page).toHaveURL(/\/demo$/)
  await expect(page.getByRole('heading', { name: /Привет, Искра/ })).toBeVisible()
  expect(await page.evaluate(() => JSON.stringify(localStorage) + JSON.stringify(sessionStorage))).not.toContain('demo-password-123')
  expect(backendRequests).toEqual([])
  expect(errors).toEqual([])
  await noOverflow(page)
})
test('auth, validation, final CTA, logo, history and standalone routes', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('main')).not.toContainText(/mock|демонстрацион|placeholder/i)
  await page.locator('.ml-header').getByRole('link', { name: 'Регистрация', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Твоя школьная жизнь — в одном месте' })).toBeVisible()
  await expect(page.getByTestId('intro-reward')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Продолжить', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await page.locator('.ml-header').getByRole('link', { name: 'Войти', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Email', { exact: true }).fill('missing@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('mock-password')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.locator('.registration-error')).toBeVisible()
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await page.getByRole('button', { name: 'Зажечь свой Маяк', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Какую планету/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Какую планету/ })).toBeInViewport()
  await page.getByRole('button', { name: 'Начать заново', exact: true }).click()
  await lightLighthouse(page)
  await page.locator('.ml-final-cta').getByRole('link', { name: 'Зажечь свой Маяк', exact: true }).click()
  await expect(page.getByTestId('intro-reward')).toBeVisible()
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Маяк зажжён!' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: /Зажги свой/ })).toBeVisible()
  await page.getByRole('link', { name: 'Попасть в рейтинг', exact: true }).click()
  await expect(page).toHaveURL(/\/register$/)
  await page.goBack()
  await expect(page.getByRole('heading', { name: /Зажги свой/ })).toBeVisible()
  for (const path of ['/about', '/rules', '/privacy', '/terms', '/support', '/login', '/register']) {
    await page.goto(path); await page.reload()
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
    await noOverflow(page)
  }
})
test('responsive layouts, shared theme, reduced motion and app return', async ({ page }) => {
  test.setTimeout(90000)
  await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'light' })
  for (const width of [320, 375, 390, 430, 768, 1024, 1280, 1440, 1920]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await expect(page.getByRole('heading', { name: /Зажги свой/ })).toBeVisible()
    await noOverflow(page)
    await expect(page.locator('.ml-header-register')).toHaveCSS('background-color', 'rgb(113, 99, 231)')
    await page.getByRole('button', { name: 'Зажечь маяк', exact: true }).click()
    await expect(page.getByRole('heading', { name: /Какую планету/ })).toBeVisible()
    await expect(page.locator('.ml-game-card')).toHaveCSS('animation-name', 'none')
    await noOverflow(page)
    await page.goto('/register')
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
    await noOverflow(page)
  }
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/')
  await page.screenshot({ path: `artifacts/landing-full-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' })
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.ml-header-register')).toHaveCSS('background-color', 'rgb(118, 100, 223)')
  await page.getByRole('button', { name: 'Зажечь маяк', exact: true }).click()
  const cardColor = await page.locator('.ml-game-card').evaluate(el => getComputedStyle(el).backgroundColor)
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'С возвращением' })).toBeVisible()
  await expect(page.locator('.registration-main')).toHaveCSS('background-color', cardColor)
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.goto('/demo')
  await page.getByRole('button', { name: 'Заглянуть в демо 9Б' }).click()
  await expect(page.locator('.app-header')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: /Зажги свой/ })).toBeVisible()
  await noOverflow(page)
})
for (const width of [375, 390, 430]) {
  test(`all tasks fit a ${width}px phone and stars stay in the play area`, async ({ page }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.setViewportSize({ width, height: 664 })
    await page.goto('/')
    await lightLighthouse(page, true)
    await noOverflow(page)
  })
}
test('the game is keyboard accessible without changing the route', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Зажечь маяк', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: /Какую планету/ })).toBeFocused()
  await page.keyboard.press('Tab'); await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Поймай 3 звезды' })).toBeFocused()
  await page.keyboard.press('Tab')
  for (let index = 1; index <= 3; index++) {
    const star = page.getByRole('button', { name: `Поймать звезду ${index}` })
    await expect(star).not.toHaveClass(/is-caught/)
    await expect(star).toBeFocused()
    await page.keyboard.press('Enter')
  }
  await expect(page.getByRole('heading', { name: 'Что зажигает твой интерес?' })).toBeFocused()
  await page.keyboard.press('Tab'); await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: /Квизы Узнавать/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Готово', exact: true }).focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Маяк зажжён!' })).toBeFocused()
  await expect(page).toHaveURL(/\/$/)
})
