import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

async function demo(page: Page) {
  await page.goto('/demo')
  await page.getByRole('button', { name: 'Заглянуть в демо 9Б', exact: true }).click()
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
}

test('bell opens preview, filters categories, marks all read and opens the full page', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await demo(page)
  const bell = page.locator('.header-bell')
  const preview = page.getByRole('dialog', { name: 'Уведомления', exact: true })
  await bell.click()
  await expect(preview).toBeVisible()
  await expect(bell).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByRole('heading', { name: 'Привет, Саша', exact: true })).toBeVisible()
  await expect(preview.getByText('У тебя 3 новых уведомления', { exact: true })).toBeVisible()
  await expect(preview.locator('.notification-preview-item')).toHaveCount(4)
  await noOverflow(page)
  await page.screenshot({ path: `artifacts/notification-preview-${testInfo.project.name}.png`, animations: 'disabled' })
  await preview.getByRole('tab', { name: /^Учёба/ }).click()
  await expect(preview.locator('.notification-preview-item')).toHaveCount(2)
  await expect(preview.getByText('Новая домашка по алгебре', { exact: true })).toBeVisible()
  await page.keyboard.press('ArrowRight')
  await expect(preview.getByRole('tab', { name: /^Общение/ })).toHaveAttribute('aria-selected', 'true')
  await expect(preview.locator('.notification-preview-item')).toHaveCount(2)
  await preview.getByRole('button', { name: 'Отметить все как прочитанные', exact: true }).click()
  await expect(preview.getByText('Все уведомления прочитаны', { exact: true })).toBeVisible()
  await expect(preview.locator('.notification-preview-unread')).toHaveCount(0)
  await expect(bell.locator('i')).toHaveCount(0)
  await expect(preview.getByRole('button', { name: 'Отметить все как прочитанные', exact: true })).toBeDisabled()
  await preview.getByRole('button', { name: 'Посмотреть все уведомления', exact: true }).click()
  await expect(preview).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Тебе есть что сказать', exact: true })).toBeVisible()
  await expect(page.locator('.notification-row')).toHaveCount(4)
  await page.getByRole('button', { name: 'Новые', exact: false }).click()
  await expect(page.getByRole('heading', { name: 'Всё прочитано', exact: true })).toBeVisible()
  await bell.click()
  await preview.getByRole('button', { name: 'Посмотреть все уведомления', exact: true }).click()
  await expect(page.locator('.notification-row')).toHaveCount(4)
  await page.reload()
  await bell.click()
  await expect(preview.getByText('Все уведомления прочитаны', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('preview closes with Escape, outside click and the bell; opening a notice marks only it read', async ({ page }) => {
  await demo(page)
  const bell = page.locator('.header-bell')
  const preview = page.getByRole('dialog', { name: 'Уведомления', exact: true })
  await bell.focus()
  await page.keyboard.press('Enter')
  await expect(preview).toBeVisible()
  await expect(preview.getByRole('tab', { name: /^Все/ })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(preview).toHaveCount(0)
  await expect(bell).toBeFocused()
  await bell.click()
  await bell.click()
  await expect(preview).toHaveCount(0)
  await bell.click()
  await page.mouse.click(4, 4)
  await expect(preview).toHaveCount(0)
  await page.setViewportSize({ width: 320, height: 740 })
  await noOverflow(page)
  await bell.click()
  await noOverflow(page)
  const bounds = await preview.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  await preview.getByRole('button', { name: /^Новая домашка по алгебре/ }).click()
  await expect(preview).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Домашка', exact: true })).toHaveAttribute('aria-selected', 'true')
  await bell.click()
  await expect(preview.getByText('У тебя 2 новых уведомления', { exact: true })).toBeVisible()
  const notice = preview.getByRole('button', { name: /^Новая домашка по алгебре/ })
  await expect(notice).toHaveClass(/\bread\b/)
  await expect(preview.locator('.notification-preview-unread')).toHaveCount(2)
  await page.reload()
  await bell.click()
  await expect(preview.getByText('У тебя 2 новых уведомления', { exact: true })).toBeVisible()
})
