import { expect, test, type Page } from '@playwright/test'
import { ageOn, suggestUsername, validateBirthDate } from '../src/features/onboarding/validation'

test.setTimeout(60000)
test.beforeEach(async ({ page }) => { await page.clock.setFixedTime(new Date('2026-10-01T09:00:00+03:00')) })
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true) }
async function account(page: Page, email = 'liza@example.test') {
  await page.goto('/register')
  await page.getByLabel('Имя', { exact: true }).fill('Лиза')
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Пароль', { exact: true }).fill('MyTestPassword2026')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Когда ты родился?', exact: true })).toBeVisible()
}
async function birthday(page: Page, year = '2010', month = '4', day = '12') {
  await page.getByRole('combobox', { name: 'День', exact: true }).selectOption(day)
  await page.getByRole('combobox', { name: 'Месяц', exact: true }).selectOption(month)
  await page.getByRole('combobox', { name: 'Год', exact: true }).selectOption(year)
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
}
async function schoolAndClass(page: Page) {
  await page.getByRole('button', { name: /ГБОУ школа №123/ }).click()
  await page.getByRole('button', { name: 'Это моя школа', exact: true }).click()
  await page.getByRole('button', { name: '9', exact: true }).click()
  await page.getByRole('button', { name: 'Б', exact: true }).click()
  await page.getByRole('button', { name: 'Присоединиться к 9Б', exact: true }).click()
}
async function accept(page: Page) {
  await page.getByRole('checkbox', { name: /Я принимаю правила сообщества и условия использования/ }).check()
  await page.getByRole('button', { name: 'Войти в Маяк', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Добро пожаловать в 9Б', exact: true })).toBeVisible()
}

test('registration: all steps, avatar, consent, welcome, persistence and local credentials', async ({ page }, testInfo) => {
  const errors: string[] = [], requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/\/(auth|api|users|schools|classes)(\/|\?)/.test(request.url())) requests.push(request.url()) })
  await account(page)
  await expect(page.getByRole('progressbar', { name: 'Регистрация' })).toHaveAttribute('aria-valuenow', '2')
  await birthday(page)
  await expect(page.getByRole('button', { name: 'Это моя школа', exact: true })).toBeDisabled()
  await schoolAndClass(page)
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Лиза')
  await expect(page.getByLabel('Username', { exact: true })).toHaveValue('liza_m')
  await page.getByLabel('Загрузить аватар', { exact: true }).setInputFiles('public/logo-reference.png')
  await expect(page.getByAltText('Твой аватар', { exact: true })).toBeVisible()
  await page.getByLabel('Username', { exact: true }).fill('liza_new')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Войти в Маяк', exact: true })).toBeDisabled()
  await page.getByRole('link', { name: 'Политика конфиденциальности', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Политика конфиденциальности', exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Понятно', exact: true }).click()
  await accept(page)
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  await expect(page.locator('.registration-summary')).toContainText('18 учеников')
  await expect(page.locator('.registration-summary')).toContainText('4 домашних задания')
  await expect(page.locator('.registration-today')).toContainText('6уроков')
  await expect(page.locator('.registration-today')).toContainText('3домашних задания')
  await page.screenshot({ path: testInfo.outputPath('welcome.png'), fullPage: true, animations: 'disabled' })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Добро пожаловать в 9Б', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Перейти в ленту', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Привет, Лиза', exact: true })).toBeVisible()
  await expect(page.locator('.post-prompt .avatar img')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Привет, Лиза', exact: true })).toBeVisible()
  const stored = await page.evaluate(() => ({ profile: JSON.parse(localStorage.getItem('mayak-profile-v1')!), user: JSON.parse(localStorage.getItem('mayak-mock-user-v1')!), all: JSON.stringify(localStorage) }))
  expect(stored.profile).toMatchObject({ username: 'liza_new', school: 'ГБОУ школа №123', className: '9Б' })
  expect(stored.user).toMatchObject({ email: 'liza@example.test', birthDate: '2010-04-12', safetyMode: 'teen' })
  expect(stored.all).not.toContain('MyTestPassword2026')
  await page.goto('/login')
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  await page.getByLabel('Email', { exact: true }).fill('liza@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('MyTestPassword2026')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Привет, Лиза', exact: true })).toBeVisible()
  await noOverflow(page)
  expect(errors).toEqual([]); expect(requests).toEqual([])
})

test('account errors, password visibility, loading and back preserve the entered data', async ({ page }, testInfo) => {
  await page.goto('/register')
  await expect(page.getByRole('button', { name: 'Продолжить', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Назад', exact: true })).toHaveCount(0)
  await page.getByLabel('Имя', { exact: true }).fill('Лиза')
  await page.getByLabel('Email', { exact: true }).fill('bad-email')
  await page.getByLabel('Пароль', { exact: true }).fill('short')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect(page.getByText(/Проверь email/)).toBeVisible()
  await expect(page.getByText('В пароле должно быть не меньше 8 символов.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Показать пароль', exact: true }).click()
  await expect(page.getByLabel('Пароль', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Скрыть пароль', exact: true }).click()
  await page.getByLabel('Email', { exact: true }).fill('liza@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('MyTestPassword2026')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Проверяем данные…', exact: true })).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Когда ты родился?', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'День', exact: true }).selectOption('12')
  await page.getByRole('button', { name: 'Назад', exact: true }).click()
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Лиза')
  await expect(page.getByLabel('Пароль', { exact: true })).toHaveValue('MyTestPassword2026')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'День', exact: true })).toHaveValue('12')
  await page.setViewportSize({ width: 320, height: 740 })
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('birth-320.png'), animations: 'disabled' })
})

test('invalid and future birthdays are rejected; under 14 cannot continue; exactly 14 can', async ({ page }) => {
  await account(page)
  await expect(page.getByText('Маяк пока доступен с 14 лет', { exact: true })).toHaveCount(0)
  await birthday(page, '2010', '2', '31')
  await expect(page.getByText('Такой даты нет. Проверь день и месяц.', { exact: true })).toBeVisible()
  await birthday(page, '2026', '10', '2')
  await expect(page.getByText('Дата рождения не может быть в будущем.', { exact: true })).toBeVisible()
  await birthday(page, '2012', '10', '2')
  await expect(page.getByRole('heading', { name: 'Маяк пока доступен с 14 лет', exact: true })).toBeVisible()
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Продолжить', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Назад', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'День', exact: true })).toHaveValue('2')
  await birthday(page, '2012', '10', '1')
  await expect(page.getByRole('heading', { name: 'Где ты учишься?', exact: true })).toBeVisible()
})

test('school not found, invite error, cross-school confirmation and skip profile', async ({ page }) => {
  await account(page)
  await birthday(page)
  await page.getByRole('textbox', { name: 'Найти школу' }).fill('не существует')
  await expect(page.getByText('Школа не найдена', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Не нашёл школу?', exact: true }).click()
  await expect(page.getByText('Добавление новых школ появится позже.', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Найти школу' }).fill('57')
  await page.getByRole('button', { name: /Школа № 57/ }).click()
  await page.getByRole('button', { name: 'Это моя школа', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Буква класса', exact: true })).toHaveCount(0)
  await page.getByLabel('Код класса', { exact: true }).fill('NOT-A-CODE')
  await page.getByRole('button', { name: 'Присоединиться', exact: true }).click()
  await expect(page.getByText(/Не нашли такой код/)).toBeVisible()
  await expect(page.getByLabel('Код класса', { exact: true })).toHaveValue('NOT-A-CODE')
  await page.getByLabel('Код класса', { exact: true }).fill('mayak-9b-74')
  await page.getByRole('button', { name: 'Присоединиться', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Это твой 9Б?', exact: true })).toBeVisible()
  await expect(page.locator('.registration-invite-confirm')).toContainText('ГБОУ школа №123')
  await page.getByRole('button', { name: 'Всё верно, присоединиться', exact: true }).click()
  await page.getByLabel('Username', { exact: true }).fill('liza_n')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await expect(page.getByText('Этот username уже занят. Попробуй другой.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Username', { exact: true })).toHaveValue('liza_n')
  await page.getByRole('button', { name: 'Пропустить', exact: true }).click()
  await accept(page)
  await page.getByRole('button', { name: 'Перейти в ленту', exact: true }).click()
  const profile = await page.evaluate(() => JSON.parse(localStorage.getItem('mayak-profile-v1')!))
  expect(profile).toMatchObject({ username: 'liza_m', school: 'ГБОУ школа №123', className: '9Б' })
  expect(profile.avatarUrl).toBeUndefined()
})

test('mock login rejects wrong credentials and accepts the demo account', async ({ page }) => {
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'С возвращением', exact: true })).toBeVisible()
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  await page.getByLabel('Email', { exact: true }).fill('sasha@mayak.demo')
  await page.getByLabel('Пароль', { exact: true }).fill('wrong-password')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByText('Email или пароль не подошли. Проверь данные и попробуй ещё раз.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('sasha@mayak.demo')
  await page.getByLabel('Пароль', { exact: true }).fill('Mayak2026')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.locator('.app-header')).toBeVisible()
})

test('failed registration storage keeps the form recoverable without creating a partial account', async ({ page }) => {
  await account(page); await birthday(page); await schoolAndClass(page)
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key: string, value: string) { if (key === 'mayak-mock-accounts-v1') throw new DOMException('Full', 'QuotaExceededError'); return original.call(this, key, value) }
  })
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Войти в Маяк', exact: true }).click()
  await expect(page.getByText(/Браузер не смог сохранить аккаунт/)).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('mayak-registration-pending-v1'))).toBeNull()
  await page.getByRole('button', { name: 'Назад', exact: true }).click()
  await expect(page.getByLabel('Username', { exact: true })).toHaveValue('liza_m')
})

test('birthday boundaries, leap days and username suggestions', () => {
  expect(ageOn('2012-10-01', '2026-10-01')).toBe(14)
  expect(ageOn('2012-10-02', '2026-10-01')).toBe(13)
  expect(ageOn('2008-10-01', '2026-10-01')).toBe(18)
  expect(validateBirthDate({ day: '29', month: '2', year: '2012' }, '2026-10-01')).toBeNull()
  expect(validateBirthDate({ day: '29', month: '2', year: '2011' }, '2026-10-01')).toContain('Такой даты нет')
  expect(suggestUsername('Лиза')).toBe('liza_m')
})

test('welcome reload and back update the same account without requiring the password again', async ({ page }) => {
  await account(page); await birthday(page); await schoolAndClass(page)
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await accept(page); await page.reload()
  await page.getByRole('button', { name: 'Назад', exact: true }).click()
  await expect(page.getByRole('checkbox')).toBeChecked()
  await page.getByRole('button', { name: 'Назад', exact: true }).click()
  await expect(page.getByLabel('Username', { exact: true })).toHaveValue('liza_m')
  await page.getByLabel('Username', { exact: true }).fill('liza_updated')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await accept(page)
  const accounts = await page.evaluate(() => JSON.parse(localStorage.getItem('mayak-mock-accounts-v1')!))
  expect(accounts).toHaveLength(1)
  expect(accounts[0].user.profile.username).toBe('liza_updated')
  await page.getByRole('button', { name: 'Перейти в ленту', exact: true }).click()
  await page.goto('/login')
  await page.getByLabel('Email', { exact: true }).fill('liza@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('MyTestPassword2026')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Привет, Лиза', exact: true })).toBeVisible()
})

test('registration rechecks uniqueness on submit and returns to the field without losing data', async ({ page }) => {
  await account(page); await birthday(page); await schoolAndClass(page)
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'В Маяке важно', exact: true })).toBeVisible()
  await page.evaluate(() => {
    localStorage.setItem('mayak-mock-accounts-v1', JSON.stringify([{ user: { id: 'other-user', email: 'other@example.test', profile: { name: 'Другой', username: 'liza_m' } }, salt: 'mock-salt', passwordDigest: 'mock-digest' }]))
  })
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Войти в Маяк', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Как тебя будут видеть в Маяке?', exact: true })).toBeVisible()
  await expect(page.getByText('Этот username уже занят. Попробуй другой.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Username', { exact: true })).toHaveValue('liza_m')
  await page.getByLabel('Username', { exact: true }).fill('liza_available')
  await page.getByRole('button', { name: 'Готово', exact: true }).click()
  await accept(page)
})

test('duplicate email and mock recovery have clear errors and do not create a new account', async ({ page }) => {
  await page.goto('/register')
  await page.getByLabel('Имя', { exact: true }).fill('Лиза')
  await page.getByLabel('Email', { exact: true }).fill('sasha@mayak.demo')
  await page.getByLabel('Пароль', { exact: true }).fill('MyTestPassword2026')
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect(page.getByText('Этот email уже зарегистрирован. Попробуй войти.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await page.getByRole('button', { name: 'Забыли пароль?', exact: true }).click()
  await page.getByLabel('Email для восстановления', { exact: true }).fill('bad-email')
  await page.getByRole('button', { name: 'Восстановить доступ', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Проверь email')
  await page.getByLabel('Email для восстановления', { exact: true }).fill('liza@example.test')
  await page.getByRole('button', { name: 'Восстановить доступ', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('письмо не отправляется')
  await page.getByRole('button', { name: 'Вернуться ко входу', exact: true }).click()
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('sasha@mayak.demo')
  expect(await page.evaluate(() => localStorage.getItem('mayak-mock-accounts-v1'))).toBeNull()
})
