import { expect, test } from '@playwright/test'

test('theme follows the system, persists overrides and can return to automatic', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light' })
  await page.goto('/demo')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Заглянуть в демо 9Б' }).click()
  const nav = await page.locator('.desktop-nav').isVisible() ? page.locator('.desktop-nav') : page.locator('.bottom-nav')
  await nav.getByRole('button', { name: /^Профиль/ }).click()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByRole('radio', { name: 'Светлая', exact: true }).check()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('.app-header')).toBeVisible()
  await nav.getByRole('button', { name: /^Профиль/ }).click()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Светлая', exact: true })).toBeChecked()
  await page.getByRole('radio', { name: 'Тёмная', exact: true }).check()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.screenshot({ path: `artifacts/theme-settings-${test.info().project.name}.png` })
  await page.getByRole('radio', { name: 'Системная', exact: true }).check()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Готово', exact: false }).click()
  await nav.getByRole('button', { name: /^Лента/ }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: `artifacts/theme-feed-${test.info().project.name}.png`, fullPage: true })
})
