import { useEffect, useRef, useState } from 'react'
import { ArrowRight, BarChart3, Camera, Check, ImagePlus, Plus, Sparkles, Upload } from 'lucide-react'
import { DEMO_DATE, initialSchedule, subjects } from '../data/mock'
import type { Homework, Lesson, Subject } from '../types'
import { DemoLabel, Modal, SubjectIcon, Tag } from './ui'

export function CreateMenu({ onClose, onPost, onPoll, onHomework, onSchedule }: { onClose: () => void; onPost: () => void; onPoll: () => void; onHomework: () => void; onSchedule: () => void }) {
  return <Modal title="Поделись чем-нибудь" onClose={onClose}><p className="modal-description">Историей, домашкой или полезной находкой.</p><div className="create-options"><button onClick={onPost}><span className="feature-icon purple"><Plus size={23} /></span><span><strong>Публикация</strong><small>От себя или без имени — решать тебе</small></span><ArrowRight size={19} /></button><button onClick={onPoll}><span className="feature-icon mint"><BarChart3 size={23} /></span><span><strong>Опрос</strong><small>Узнай, что думают свои</small></span><ArrowRight size={19} /></button><button onClick={onHomework}><span className="feature-icon blue"><Check size={23} /></span><span><strong>Домашнее задание</strong><small>Вручную или по фотографии</small></span><ArrowRight size={19} /></button><button onClick={onSchedule}><span className="feature-icon pink"><Camera size={23} /></span><span><strong>Расписание по фото</strong><small>Одно фото — вся неделя под рукой</small></span><ArrowRight size={19} /></button></div></Modal>
}
export { default as PostComposer } from './PostComposer'

export function HomeworkComposer({ onClose, onSave }: { onClose: () => void; onSave: (homework: Homework) => void }) {
  const [mode, setMode] = useState<'manual' | 'photo'>('manual')
  const [subject, setSubject] = useState<Subject>('Алгебра')
  const [text, setText] = useState('')
  const [date, setDate] = useState('2026-10-01')
  const [minutes, setMinutes] = useState(20)
  const [scanned, setScanned] = useState(false)
  return <Modal title="Добавим домашку" onClose={onClose}><div className="digest-period"><button className={mode === 'manual' ? 'active' : ''} onClick={() => setMode('manual')}>✏️ Вручную</button><button className={mode === 'photo' ? 'active' : ''} onClick={() => setMode('photo')}>📷 По фотографии</button></div>{mode === 'photo' ? <PhotoScanner kind="homework" onReady={() => { setSubject('Геометрия'); setText('№ 112, 114. Повторить признаки подобия треугольников'); setMinutes(25); setScanned(true); setMode('manual') }} /> : <form onSubmit={e => { e.preventDefault(); if (!text.trim()) return; onSave({ id: crypto.randomUUID(), subject, text: text.trim(), date, minutes, done: false, source: scanned ? 'Демо-распознавание фото' : 'Добавлено тобой' }) }}>{scanned && <div className="recognized-note"><Sparkles size={17} />Пример распознан. Проверь и поправь, если нужно.</div>}<label className="field-label" htmlFor="hw-subject">Предмет</label><select className="input" id="hw-subject" value={subject} onChange={e => setSubject(e.target.value as Subject)}>{Object.keys(subjects).map(s => <option key={s}>{s}</option>)}</select><label className="field-label" htmlFor="hw-text">Что задали?</label><textarea id="hw-text" className="input homework-textarea" required maxLength={1000} placeholder="Параграф, упражнение или небольшой план…" value={text} onChange={e => setText(e.target.value)} /><div className="form-row"><label><span className="field-label">На когда</span><input aria-label="Срок домашнего задания" className="input" type="date" required min={DEMO_DATE} value={date} onChange={e => setDate(e.target.value)} /></label><label><span className="field-label">Примерно минут</span><input className="input" aria-label="Время на домашнее задание" type="number" min={5} max={180} step={5} value={minutes} required onChange={e => setMinutes(Number(e.target.value))} /></label></div><button className="button primary full" disabled={!text.trim() || !date || minutes < 5 || minutes > 180}>Добавить задание<Plus size={17} /></button></form>}</Modal>
}
function PhotoScanner({ kind, onReady }: { kind: 'homework' | 'schedule'; onReady: () => void }) {
  const [preview, setPreview] = useState<string | null>(null)
  const [filename, setFilename] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const input = useRef<HTMLInputElement>(null)
  const callback = useRef(onReady)
  callback.current = onReady
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current) }, [])
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview) }, [preview])
  function scan() { setLoading(true); timer.current = setTimeout(() => { setLoading(false); callback.current() }, 1900) }
  return <div className="photo-scanner"><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" aria-label="Выбрать фотографию" className="visually-hidden" onChange={e => { const file = e.target.files?.[0]; if (!file) return; if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type)) { setError('Выбери фото в формате JPG, PNG или WebP.'); return } if (file.size > 8 * 1024 * 1024) { setError('Фото должно быть меньше 8 МБ.'); return } setError(''); setPreview(URL.createObjectURL(file)); setFilename(file.name) }} />{loading ? <div className="scan-loading" role="status"><div className="scan-orb"><Sparkles size={34} /></div><h3>Находим главное…</h3><p>{kind === 'schedule' ? 'Предметы, время и кабинеты' : 'Предмет, задание и дату'}</p><div className="scan-progress"><i /></div><DemoLabel>Имитация распознавания</DemoLabel></div> : <><button className={`photo-dropzone ${preview ? 'has-preview' : ''}`} onClick={() => input.current?.click()}>{preview ? <><img src={preview} alt="Выбранное фото для демо-распознавания" /><span>{filename}<small>Нажми, чтобы выбрать другое фото</small></span></> : <><span className="feature-icon purple"><ImagePlus size={32} /></span><strong>{kind === 'schedule' ? 'Фото расписания' : 'Фото доски или тетради'}</strong><p>Выбери фотографию с устройства</p><span className="upload-formats">JPG, PNG, WebP · до 8 МБ</span></>}</button>{error && <p className="field-error" role="alert">{error}</p>}{preview && <button className="button primary full" onClick={scan}><Sparkles size={17} />Распознать пример</button>}<button className={`button ${preview ? 'ghost' : 'secondary'} full`} onClick={scan}><Upload size={17} />Попробовать на демо-фото</button><p className="scan-disclaimer">В MVP фото остаётся на устройстве. Результат — заранее подготовленный пример, который можно отредактировать.</p></>}</div>
}
export function ScheduleImport({ onClose, onSave }: { onClose: () => void; onSave: (schedule: Lesson[][]) => void }) {
  const [ready, setReady] = useState(false)
  const [schedule, setSchedule] = useState<Lesson[][]>(() => structuredClone(initialSchedule))
  const [day, setDay] = useState(2)
  function update(index: number, patch: Partial<Lesson>) { setSchedule(s => s.map((d, di) => di === day ? d.map((l, i) => i === index ? { ...l, ...patch } : l) : d)) }
  return <Modal title={ready ? 'Проверь расписание' : 'Расписание по фотографии'} onClose={onClose} wide={ready}>{!ready ? <PhotoScanner kind="schedule" onReady={() => setReady(true)} /> : <><div className="recognized-note"><Sparkles size={17} />Нашли 5 дней и 29 уроков в демо-примере</div><p className="modal-description">Проверь предметы и кабинеты. Любую строку можно поправить.</p><div className="digest-period scan-day-picker">{['Пн', 'Вт', 'Ср', 'Чт', 'Пт'].map((d, i) => <button key={d} className={day === i ? 'active' : ''} onClick={() => setDay(i)}>{d}</button>)}</div><div className="scan-results">{schedule[day].map((l, i) => <div className="scan-result-row" key={i}><SubjectIcon subject={l.subject} /><div><select className="input" aria-label={`Предмет ${i + 1}`} value={l.subject} onChange={e => { const subject = e.target.value as Subject; update(i, { subject, teacher: subjects[subject].teacher }) }}>{Object.keys(subjects).map(s => <option key={s}>{s}</option>)}</select><span>{l.time}</span></div><label><span>Кабинет</span><input className="input" aria-label={`Кабинет ${i + 1}`} value={l.room} maxLength={12} required onChange={e => update(i, { room: e.target.value })} /></label></div>)}</div><button className="button primary full" disabled={schedule.some(d => d.some(l => !l.room.trim()))} onClick={() => onSave(schedule)}><Check size={18} />Сохранить неделю</button><p className="inline-demo"><Tag>Демо-результат</Tag><span>Сохранится локально в твоём расписании.</span></p></>}</Modal>
}
