import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronRight, GraduationCap, Heart, MapPin, Search, Sparkles, Users } from 'lucide-react'
import { defaultProfile, schools } from '../data/mock'
import type { Profile } from '../types'
import { Avatar, Brand, Lighthouse } from './ui'

export default function Onboarding({ onFinish }: { onFinish: (profile: Profile) => void }) {
  const [step, setStep] = useState(0)
  const [query, setQuery] = useState('')
  const [school, setSchool] = useState(defaultProfile.school)
  const [grade, setGrade] = useState(9)
  const [letter, setLetter] = useState('Б')
  const [name, setName] = useState('')
  return <div className="onboarding"><header className="onboarding-header"><Brand /><span className="onboarding-tagline">На одной волне</span></header><div className="onboarding-layout">
    <section className="onboarding-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="onboarding-art"><Lighthouse /><span className="floating-spark spark-one">✦</span><span className="floating-spark spark-two">✧</span></div><div className="float-card float-friends"><div className="avatar-stack"><Avatar person="masha" /><Avatar person="artem" /><Avatar person="dasha" /></div><span>Свои люди — рядом<Heart size={14} /></span></div><div className="float-card float-study"><span className="subject-icon purple">∑</span><div><strong>С алгеброй разберёмся</strong><span>По шагам, без стресса</span></div><Sparkles size={19} /></div><div className="visual-caption"><span>ТВОЁ МЕСТО. ТВОЙ МАЯК.</span><h2>Школа — это<br />больше, чем уроки.</h2></div></section>
    <section className="onboarding-content"><div className="onboarding-progress" aria-label={`Шаг ${step + 1} из 3`}>{[0, 1, 2].map(i => <span key={i} className={i <= step ? 'active' : ''} />)}</div>
      {step === 0 && <><span className="eyebrow">ПРИВЕТ, ЭТО МАЯК 👋</span><h1>Сделано для<br /><span className="gradient-text">школьника,</span><br />а не школы.</h1><p className="onboarding-description">Твой класс, твои планы и немного помощи<br className="desktop-break" /> с учёбой. Всё в одном месте.</p><div className="onboarding-features"><div><span className="feature-icon pink"><Users size={19} /></span><span>Общайся со своими</span></div><div><span className="feature-icon blue"><GraduationCap size={19} /></span><span>Держи учёбу под рукой</span></div><div><span className="feature-icon purple"><Sparkles size={19} /></span><span>Разбирайся вместе с AI</span></div></div><button className="button primary full" onClick={() => setStep(1)}>Найти свой класс<ArrowRight size={18} /></button><button className="demo-entry" onClick={() => onFinish(defaultProfile)}>Заглянуть в демо 9Б<ChevronRight size={16} /></button><p className="onboarding-footnote">Без оценок за общение. Просто будь собой.</p></>}
      {step === 1 && <><button className="back-link" onClick={() => setStep(0)}><ArrowLeft size={16} />Назад</button><span className="eyebrow">ШАГ 1 · ТВОЯ ШКОЛА</span><h1>Где учатся<br /><span className="gradient-text">твои люди?</span></h1><p className="onboarding-description">Найди школу, чтобы быть на одной волне.</p><label className="search-field"><Search size={19} /><input aria-label="Найти школу" placeholder="Название или номер школы" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="school-list">{schools.filter(s => s.toLowerCase().includes(query.toLowerCase())).map(s => <button key={s} className={`school-option ${s === school ? 'selected' : ''}`} onClick={() => setSchool(s)}><span className="feature-icon blue"><GraduationCap size={22} /></span><span><strong>{s}</strong><small><MapPin size={12} />Москва</small></span>{s === school ? <span className="selection-check"><Check size={15} /></span> : <ChevronRight size={17} />}</button>)}{!schools.some(s => s.toLowerCase().includes(query.toLowerCase())) && <div className="empty-search">В демо доступны четыре школы. Попробуй другой номер.</div>}</div><button className="button primary full" onClick={() => setStep(2)}>Дальше<ArrowRight size={18} /></button><p className="onboarding-footnote">Пока знакомимся на примере демо-школ.</p></>}
      {step === 2 && <><button className="back-link" onClick={() => setStep(1)}><ArrowLeft size={16} />Назад</button><span className="eyebrow">ШАГ 2 · ТВОЙ КЛАСС</span><h1>Давай найдём<br /><span className="gradient-text">своих.</span></h1><p className="onboarding-description">{school} · Москва</p><form onSubmit={e => { e.preventDefault(); if (name.trim()) onFinish({ ...defaultProfile, school, className: `${grade}${letter}`, name: name.trim() }) }}><label className="field-label" htmlFor="profile-name">Как тебя зовут?</label><input id="profile-name" className="input" autoComplete="given-name" maxLength={30} placeholder="Например, Саша" value={name} required onChange={e => setName(e.target.value)} /><label className="field-label">В каком ты классе?</label><div className="grade-picker">{[7, 8, 9, 10, 11].map(g => <button key={g} type="button" className={grade === g ? 'selected' : ''} aria-pressed={grade === g} onClick={() => setGrade(g)}>{g}</button>)}</div><div className="letter-picker">{['А', 'Б', 'В', 'Г', 'Д'].map(l => <button key={l} type="button" className={letter === l ? 'selected' : ''} aria-pressed={letter === l} onClick={() => setLetter(l)}>{l}</button>)}</div><div className="join-preview"><div className="class-avatar">{grade}{letter}</div><div><strong>Твоё пространство — {grade}{letter}</strong><span>Демо-расписание и публикации уже внутри</span></div></div><button className="button primary full" disabled={!name.trim()} type="submit">Погнали<ArrowRight size={18} /></button></form><p className="onboarding-footnote">Тебя уже ждут хорошие истории ✨</p></>}
    </section></div><footer className="onboarding-footer"><span>© Маяк, 2026</span><span>Чуть меньше стресса. Чуть больше тебя.</span></footer></div>
}
