import { useEffect, useRef, useState } from 'react'
import { ArrowRight, BookOpen, CalendarDays, Camera, Check, ChevronRight, Clock3, GraduationCap, Plus, Send, Sparkles, Sun } from 'lucide-react'
import { DEMO_DATE, subjects, tutorReplies } from '../data/mock'
import { useStoredState } from '../hooks/useStoredState'
import type { ChatMessage, Homework, Lesson, StudyTab, Subject } from '../types'
import { DemoLabel, Empty, Modal, SectionTitle, SubjectIcon, Tag } from './ui'

interface Props {
  active: StudyTab; setActive: (tab: StudyTab) => void; schedule: Lesson[][]; homework: Homework[];
  onToggle: (id: string) => void; onAdd: () => void; onScan: () => void;
  onDigest: (period: 'morning' | 'evening') => void; className: string
}
export function HomeworkItem({ homework, onToggle, onClick }: { homework: Homework; onToggle: () => void; onClick: () => void }) {
  return <div className={`homework-item ${homework.done ? 'done' : ''}`}><button className="homework-check" aria-label={`${homework.done ? 'Вернуть в работу' : 'Завершить'}: ${homework.subject}`} aria-pressed={homework.done} onClick={onToggle}>{homework.done && <Check size={15} />}</button><button className="homework-content" onClick={onClick}><span><strong>{homework.subject}</strong><span className="homework-time"><Clock3 size={12} />{homework.minutes} мин</span></span><p>{homework.text}</p><small>{homework.date === '2026-10-01' ? 'На завтра' : formatDate(homework.date)}<span>·</span>{homework.source}</small></button><ChevronRight size={16} className="muted" /></div>
}
function formatDate(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' }) }
export default function Study({ active, setActive, schedule, homework, onToggle, onAdd, onScan, onDigest, className }: Props) {
  const [day, setDay] = useState(2)
  const [filter, setFilter] = useState('pending')
  const [detailId, setDetailId] = useState<string | null>(null)
  const [lesson, setLesson] = useState<Lesson | null>(null)
  const [tutorPrompt, setTutorPrompt] = useState('')
  const detail = homework.find(h => h.id === detailId)
  const pendingTomorrow = homework.filter(h => !h.done && h.date === '2026-10-01')
  const tomorrow = homework.filter(h => h.date === '2026-10-01')
  const done = tomorrow.filter(h => h.done).length
  const tabs: { id: StudyTab; label: string }[] = [{ id: 'today', label: 'Сегодня' }, { id: 'schedule', label: 'Расписание' }, { id: 'homework', label: 'Домашка' }, { id: 'tutor', label: 'AI-репетитор' }]
  const askTutor = (subject: Subject) => { setTutorPrompt(subject === 'Физика' ? 'Объясни ускорение' : subject === 'Русский язык' ? 'Объясни сложные предложения' : 'Как решать квадратные уравнения?'); setActive('tutor'); setDetailId(null) }
  return <><div className="page-heading"><div><span className="eyebrow">ЧУТЬ МЕНЬШЕ СТРЕССА</span><h1>Учёба под рукой</h1><p>Ты справишься. А мы поможем.</p></div><span className="page-symbol blue"><GraduationCap size={27} /></span></div><div className="study-tabs" role="tablist" aria-label="Разделы учёбы">{tabs.map(t => <button key={t.id} role="tab" aria-selected={active === t.id} className={active === t.id ? 'active' : ''} onClick={() => setActive(t.id)}>{t.label}</button>)}</div>
    {active === 'today' && <><div className="today-digest"><div className="digest-top"><span><Sparkles size={17} />ТВОЁ УТРО В ДВУХ СЛОВАХ</span><Sun size={24} /></div><h2>День хороший. Ты готов.</h2><p>Сегодня {schedule[2].length} уроков, физика в 315-м,<br />а после — время для себя.</p><button onClick={() => onDigest('morning')}>Читать утренний дайджест<ArrowRight size={16} /></button><div className="digest-sun" /></div><div className="today-stats"><div><span className="feature-icon purple"><BookOpen size={19} /></span><strong>{schedule[2].length}<small>уроков сегодня</small></strong></div><div><span className="feature-icon orange"><Clock3 size={19} /></span><strong>{pendingTomorrow.reduce((n, h) => n + h.minutes, 0)} мин<small>домашки на завтра</small></strong></div></div><SectionTitle title="Сегодня · среда" action="Вся неделя" onClick={() => setActive('schedule')} /><div className="card lesson-list">{schedule[2].map((l, i) => <button key={i} className={`lesson-row ${i === 2 ? 'current' : ''}`} onClick={() => setLesson(l)}><span className="lesson-number">{i + 1}</span><SubjectIcon subject={l.subject} /><span className="lesson-info"><strong>{l.subject}{i === 2 && <span className="current-label">СЕЙЧАС В ДЕМО</span>}</strong><small>{l.time}<span>·</span>{l.room === 'Спортзал' ? l.room : `Каб. ${l.room}`}</small></span><ChevronRight size={15} /></button>)}</div><SectionTitle title="Домашка на завтра" action="Вся домашка" onClick={() => setActive('homework')} /><div className="card homework-card"><div className="homework-progress"><span>{done} из {tomorrow.length} готово</span><div><i style={{ width: `${tomorrow.length ? done / tomorrow.length * 100 : 100}%` }} /></div><span>Ты молодец ✨</span></div>{tomorrow.map(h => <HomeworkItem key={h.id} homework={h} onToggle={() => onToggle(h.id)} onClick={() => setDetailId(h.id)} />)}{!tomorrow.length && <Empty title="Завтра без домашки">Больше времени для своих планов.</Empty>}</div><button className="evening-link" onClick={() => onDigest('evening')}><span>🌙</span><div><strong>А вечером — выдохнем</strong><p>Посмотрим, что получилось, и соберёмся на завтра</p></div><ArrowRight size={18} /></button></>}
    {active === 'schedule' && <><div className="section-title schedule-heading"><div><h2>28 сентября — 2 октября</h2><p>Расписание {className} · учебная неделя</p></div><button className="icon-button outlined" aria-label="Загрузить расписание по фото" onClick={onScan}><Camera size={19} /></button></div><div className="week-picker">{['Пн', 'Вт', 'Ср', 'Чт', 'Пт'].map((label, i) => <button key={label} aria-pressed={day === i} className={day === i ? 'active' : ''} onClick={() => setDay(i)}><span>{label}</span><strong>{[28, 29, 30, 1, 2][i]}</strong>{i === 2 && <i />}</button>)}</div><div className="card lesson-list">{schedule[day].map((l, i) => <button key={i} className="lesson-row" onClick={() => setLesson(l)}><span className="lesson-number">{i + 1}</span><SubjectIcon subject={l.subject} /><span className="lesson-info"><strong>{l.subject}</strong><small>{l.time}<span>·</span>{l.room === 'Спортзал' ? l.room : `Каб. ${l.room}`}</small></span><ChevronRight size={15} /></button>)}</div><div className="schedule-end"><span>☁️</span>После {schedule[day].at(-1)?.time.split('–')[1]} — твои планы.</div><button className="upload-banner" onClick={onScan}><span className="feature-icon purple"><Camera size={23} /></span><div><strong>Расписание есть на фото?</strong><p>Маяк перенесёт его сюда. Ты только проверь.</p></div><ArrowRight size={19} /></button><div className="inline-demo"><DemoLabel>Распознавание в демо</DemoLabel><span>Используем подготовленный пример расписания.</span></div></>}
    {active === 'homework' && <><div className="section-title"><div><h2>По одному делу за раз</h2><p>{homework.filter(h => !h.done).length} заданий ждут тебя</p></div><button className="button primary small-button" onClick={onAdd}><Plus size={16} />Добавить</button></div><div className="pill-tabs">{[{ id: 'pending', text: 'Сделать' }, { id: 'done', text: 'Готово' }, { id: 'all', text: 'Все' }].map(f => <button key={f.id} className={filter === f.id ? 'active' : ''} onClick={() => setFilter(f.id)}>{f.text}<span>{homework.filter(h => f.id === 'all' || (f.id === 'done' ? h.done : !h.done)).length}</span></button>)}</div><div className="card homework-card">{homework.filter(h => filter === 'all' || (filter === 'done' ? h.done : !h.done)).sort((a, b) => a.date.localeCompare(b.date)).map(h => <HomeworkItem key={h.id} homework={h} onToggle={() => onToggle(h.id)} onClick={() => setDetailId(h.id)} />)}{!homework.some(h => filter === 'all' || (filter === 'done' ? h.done : !h.done)) && <Empty title={filter === 'done' ? 'Первая маленькая победа впереди' : 'Всё сделано. Вот это ты!'}>{filter === 'done' ? 'Отмечай готовые задания — они появятся здесь.' : 'Можно заняться чем-нибудь приятным.'}</Empty>}</div><button className="upload-banner" onClick={onAdd}><span className="feature-icon blue"><Camera size={23} /></span><div><strong>Сфоткай — и готово</strong><p>Добавь домашку с доски или из тетради.</p></div><ArrowRight size={19} /></button></>}
    {active === 'tutor' && <Tutor initialPrompt={tutorPrompt} />}
    {detail && <Modal title={detail.subject} onClose={() => setDetailId(null)}><div className="homework-detail"><SubjectIcon subject={detail.subject} /><Tag color="blue">{formatDate(detail.date)}</Tag><h3>{detail.text}</h3><p><Clock3 size={16} />Примерно {detail.minutes} минут<span>·</span>{detail.source}</p><button className={`button ${detail.done ? 'secondary' : 'primary'} full`} onClick={() => { onToggle(detail.id); setDetailId(null) }}><Check size={18} />{detail.done ? 'Вернуть в работу' : 'Готово, я справился'}</button><button className="button secondary full" onClick={() => askTutor(detail.subject)}><Sparkles size={17} />Разобраться с AI-репетитором</button></div></Modal>}
    {lesson && <Modal title={lesson.subject} onClose={() => setLesson(null)}><div className="lesson-detail"><SubjectIcon subject={lesson.subject} /><h3>{lesson.subject}</h3><p>{lesson.teacher}</p><div className="detail-meta"><span><Clock3 size={17} />{lesson.time}</span><span><CalendarDays size={17} />{lesson.room === 'Спортзал' ? lesson.room : `Кабинет ${lesson.room}`}</span></div><h4>Домашка по предмету</h4>{homework.filter(h => h.subject === lesson.subject).map(h => <HomeworkItem key={h.id} homework={h} onToggle={() => onToggle(h.id)} onClick={() => { setLesson(null); setDetailId(h.id) }} />)}{!homework.some(h => h.subject === lesson.subject) && <p className="soft-note">Заданий пока нет. Добавь, если что-то задали.</p>}<button className="button secondary full" onClick={() => { setLesson(null); onAdd() }}><Plus size={17} />Добавить задание</button></div></Modal>}
  </>
}
function Tutor({ initialPrompt }: { initialPrompt: string }) {
  const [messages, setMessages] = useStoredState<ChatMessage[]>('mayak-chat-v1', [{ id: 'hello', role: 'assistant', text: 'Привет! Давай разберём сложное вместе ✨\nЯ объясняю по шагам и без спешки. С чего начнём?' }])
  const [input, setInput] = useState(initialPrompt)
  const [thinking, setThinking] = useState(false)
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const end = useRef<HTMLDivElement>(null)
  useEffect(() => { return () => { if (timer.current) clearTimeout(timer.current) } }, [])
  useEffect(() => { end.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }) }, [messages, thinking])
  function send(text: string) {
    if (!text.trim() || thinking) return
    setMessages(m => [...m, { id: crypto.randomUUID(), role: 'user', text: text.trim() }]); setInput(''); setThinking(true)
    const lower = text.toLowerCase()
    const reply = /квадрат|алгебр|уравнен|дискриминант/.test(lower) ? tutorReplies.quadratic : /ускорен|физик|скорост/.test(lower) ? tutorReplies.physics : /предложен|русск|союз/.test(lower) ? tutorReplies.russian : tutorReplies.fallback
    timer.current = setTimeout(() => { setMessages(m => [...m, { id: crypto.randomUUID(), role: 'assistant', text: reply }]); setThinking(false) }, 1300)
  }
  return <div className="tutor"><div className="tutor-heading"><span className="ai-avatar"><Sparkles size={24} /></span><div><h2>Твой AI-репетитор</h2><span><i />На твоей стороне</span></div><DemoLabel /></div><div className="tutor-topics">{['Квадратные уравнения', 'Ускорение', 'Сложные предложения'].map(topic => <button key={topic} disabled={thinking} onClick={() => send(`Объясни: ${topic}`)}>{topic}<Plus size={12} /></button>)}</div><div className="chat-messages">{messages.map(m => <div className={`chat-message ${m.role}`} key={m.id}>{m.role === 'assistant' && <span className="chat-spark"><Sparkles size={15} /></span>}<p>{m.text}</p></div>)}{thinking && <div className="typing-indicator" role="status" aria-label="Репетитор готовит ответ"><span /><span /><span /></div>}<div ref={end} /></div><form className="message-input" onSubmit={e => { e.preventDefault(); send(input) }}><input aria-label="Вопрос AI-репетитору" maxLength={1000} placeholder="Что хочется понять?" value={input} onChange={e => setInput(e.target.value)} /><button className="send-button" aria-label="Отправить вопрос" disabled={!input.trim() || thinking}><Send size={18} /></button></form><p className="tutor-footnote">Демо с подготовленными ответами · настоящее AI подключим позже</p></div>
}
export function Digest({ period, setPeriod, schedule, homework, onClose, onStudy }: { period: 'morning' | 'evening'; setPeriod: (period: 'morning' | 'evening') => void; schedule: Lesson[][]; homework: Homework[]; onClose: () => void; onStudy: () => void }) {
  const done = homework.filter(h => h.done).length
  const pending = homework.filter(h => !h.done && h.date === '2026-10-01')
  return <Modal title="Твой день с Маяком" onClose={onClose}><div className="digest-period"><button className={period === 'morning' ? 'active' : ''} onClick={() => setPeriod('morning')}>☀️ Утро</button><button className={period === 'evening' ? 'active' : ''} onClick={() => setPeriod('evening')}>🌙 Вечер</button></div><div className={`digest-content ${period}`}><span className="digest-emoji">{period === 'morning' ? '☀️' : '🌙'}</span><span className="eyebrow">{period === 'morning' ? 'СРЕДА, 30 СЕНТЯБРЯ · 07:30' : 'СРЕДА, 30 СЕНТЯБРЯ · 20:00'}</span><h2>{period === 'morning' ? 'Хороший день начинается с тебя.' : 'Ты сегодня многое успел.'}</h2><p>{period === 'morning' ? `Сегодня ${schedule[2].length} уроков. Первый — ${schedule[2][0].subject.toLowerCase()}, в ${schedule[2][0].time.split('–')[0]}. Не забудь тетрадь и что-нибудь на перекус.` : `${done} ${done === 1 ? 'задание уже готово' : 'заданий уже готово'} — это маленькие победы, из которых складывается большой день.`}</p><div className="digest-block"><strong>{period === 'morning' ? '📚 На что обратить внимание' : '🎒 Соберёмся на завтра'}</strong><p>{period === 'morning' ? 'Физика — в кабинете 315. На физкультуру возьми форму. После шестого урока в 14:10 ты свободен!' : `Завтра начнём с ${schedule[3][0].subject === 'Геометрия' ? 'геометрии' : schedule[3][0].subject.toLowerCase()}. В расписании ${schedule[3].length} уроков.`}</p></div><div className="digest-block"><strong>{period === 'morning' ? '✏️ Домашка без суеты' : '✨ Осталось совсем немного'}</strong><p>{pending.length ? `На завтра осталось ${pending.length} задания: ${pending.map(h => h.subject.toLowerCase()).join(', ')}. Примерно ${pending.reduce((sum, h) => sum + h.minutes, 0)} минут. Начни с одного.` : 'Домашка на завтра готова. Вечер можно посвятить себе.'}</p></div><p className="digest-wish">{period === 'morning' ? 'Не обязательно успеть всё. Просто начни 🌿' : 'Отложи телефон чуть пораньше. Ты заслужил отдых 💜'}</p></div><button className="button primary full" onClick={onStudy}>Открыть учёбу<ArrowRight size={17} /></button><p className="inline-demo"><DemoLabel>AI-дайджест · демо</DemoLabel><span>Подготовленный текст и данные твоего класса.</span></p></Modal>
}
export { DEMO_DATE, subjects }
