import { ArrowDownRight as LucideArrowDownRight, ArrowLeft as LucideArrowLeft, ArrowRight as LucideArrowRight, ArrowUpRight as LucideArrowUpRight, Atom as LucideAtom, Backpack as LucideBackpack, BarChart3 as LucideBarChart3, Bell as LucideBell, BookOpen as LucideBookOpen, Bookmark as LucideBookmark, Calculator as LucideCalculator, CalendarDays as LucideCalendarDays, Camera as LucideCamera, Check as LucideCheck, CheckCheck as LucideCheckCheck, ChevronDown as LucideChevronDown, ChevronLeft as LucideChevronLeft, ChevronRight as LucideChevronRight, Clock3 as LucideClock3, Cloud as LucideCloud, Code2 as LucideCode2, Dumbbell as LucideDumbbell, Flag as LucideFlag, Flame as LucideFlame, FlaskConical as LucideFlaskConical, Globe2 as LucideGlobe2, GraduationCap as LucideGraduationCap, HandHeart as LucideHandHeart, Heart as LucideHeart, Hourglass as LucideHourglass, ImagePlus as LucideImagePlus, Languages as LucideLanguages, LayoutGrid as LucideLayoutGrid, Leaf as LucideLeaf, ListOrdered as LucideListOrdered, LoaderCircle as LucideLoaderCircle, MapPin as LucideMapPin, MessageCircle as LucideMessageCircle, Moon as LucideMoon, MoreHorizontal as LucideMoreHorizontal, Music2 as LucideMusic2, Newspaper as LucideNewspaper, Pencil as LucidePencil, Plus as LucidePlus, RotateCcw as LucideRotateCcw, Search as LucideSearch, Send as LucideSend, Settings2 as LucideSettings2, Share2 as LucideShare2, Shield as LucideShield, Smile as LucideSmile, Sparkles as LucideSparkles, Sun as LucideSun, Trash2 as LucideTrash2, TrendingUp as LucideTrendingUp, Triangle as LucideTriangle, Upload as LucideUpload, UserRound as LucideUserRound, Users as LucideUsers, UsersRound as LucideUsersRound, X as LucideX } from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'
import { ArrowDown as LucideArrowDown, Brain as LucideBrain, Gamepad2 as LucideGamepad2, Palette as LucidePalette, Star as LucideStar, Trophy as LucideTrophy } from 'lucide-react'

// Functional icons share one geometry, even in active or selected states.
export const ICON_SIZE = 24
export const ICON_STROKE = 2.5

function outline(Component: LucideIcon) {
  return function OutlineIcon(props: LucideProps) {
    return <Component {...props} size={ICON_SIZE} strokeWidth={ICON_STROKE} absoluteStrokeWidth fill="none" strokeLinecap="round" strokeLinejoin="round" className={`mayak-icon ${props.className ?? ''}`} />
  }
}

export const ArrowDownRight = outline(LucideArrowDownRight)
export const ArrowLeft = outline(LucideArrowLeft)
export const ArrowRight = outline(LucideArrowRight)
export const ArrowUpRight = outline(LucideArrowUpRight)
export const Atom = outline(LucideAtom)
export const Backpack = outline(LucideBackpack)
export const BarChart3 = outline(LucideBarChart3)
export const Bell = outline(LucideBell)
export const BookOpen = outline(LucideBookOpen)
export const Bookmark = outline(LucideBookmark)
export const Calculator = outline(LucideCalculator)
export const CalendarDays = outline(LucideCalendarDays)
export const Camera = outline(LucideCamera)
export const Check = outline(LucideCheck)
export const CheckCheck = outline(LucideCheckCheck)
export const ChevronDown = outline(LucideChevronDown)
export const ChevronLeft = outline(LucideChevronLeft)
export const ChevronRight = outline(LucideChevronRight)
export const Clock3 = outline(LucideClock3)
export const Cloud = outline(LucideCloud)
export const Code2 = outline(LucideCode2)
export const Dumbbell = outline(LucideDumbbell)
export const Flag = outline(LucideFlag)
export const Flame = outline(LucideFlame)
export const FlaskConical = outline(LucideFlaskConical)
export const Globe2 = outline(LucideGlobe2)
export const GraduationCap = outline(LucideGraduationCap)
export const HandHeart = outline(LucideHandHeart)
export const Heart = outline(LucideHeart)
export const Hourglass = outline(LucideHourglass)
export const ImagePlus = outline(LucideImagePlus)
export const Languages = outline(LucideLanguages)
export const LayoutGrid = outline(LucideLayoutGrid)
export const Leaf = outline(LucideLeaf)
export const ListOrdered = outline(LucideListOrdered)
export const LoaderCircle = outline(LucideLoaderCircle)
export const MapPin = outline(LucideMapPin)
export const MessageCircle = outline(LucideMessageCircle)
export const Moon = outline(LucideMoon)
export const MoreHorizontal = outline(LucideMoreHorizontal)
export const Music2 = outline(LucideMusic2)
export const Newspaper = outline(LucideNewspaper)
export const Pencil = outline(LucidePencil)
export const Plus = outline(LucidePlus)
export const RotateCcw = outline(LucideRotateCcw)
export const Search = outline(LucideSearch)
export const Send = outline(LucideSend)
export const Settings2 = outline(LucideSettings2)
export const Share2 = outline(LucideShare2)
export const Shield = outline(LucideShield)
export const Smile = outline(LucideSmile)
export const Sparkles = outline(LucideSparkles)
export const Sun = outline(LucideSun)
export const Trash2 = outline(LucideTrash2)
export const TrendingUp = outline(LucideTrendingUp)
export const Triangle = outline(LucideTriangle)
export const Upload = outline(LucideUpload)
export const UserRound = outline(LucideUserRound)
export const Users = outline(LucideUsers)
export const UsersRound = outline(LucideUsersRound)
export const X = outline(LucideX)
export const ArrowDown = outline(LucideArrowDown)
export const Brain = outline(LucideBrain)
export const Gamepad2 = outline(LucideGamepad2)
export const Palette = outline(LucidePalette)
export const Star = outline(LucideStar)
export const Trophy = outline(LucideTrophy)
